### ISSUE TITLE
valet share command needs support for ngrok -subdomain and -region params

### ISSUE THREAD

**Issue by leonardoamx** [cretueusebiu/valet-windows#102]
In Unix, you can type `valet share [-subdomain=project] [-region=us]` to define a custom url (project.ngrok.io or project.us.ngrok.io) but this package has `valet share` command declared with no params.

https://github.com/cretueusebiu/valet-windows/blob/34fceb1cae2e4b0bc83ab3a1102281e45680d3c7/cli/valet.php#L203

**Comment by cretueusebiu** [comment]
Added in 2.2.0.
