### ISSUE TITLE
Using on Corporate Network

### ISSUE THREAD

**Issue by LarBearrr** [cretueusebiu/valet-windows#104]
I'm hoping to get this setup on my Windows machine at work and seem to be having a couple of issues:

1) When changing my DNS settings to use 127.0.0.1 as primary, and our corporate DNS as secondary, I seem to lose access to the network but internet access still works.
2) I have to disable IIS in Windows (which is fine).

The Valet service seems to be working fine as I am able to ping and view sites such as "app.test" but I cannot access my corporate network.

Has anyone ran into a similar issue or have any suggestions?

Thank you!

**Comment by dev-manvir** [comment]
@LarBearrr i agree with you, but currently i didn't find any solution regarding to this. So i am using hosts file.

**Comment by cretueusebiu** [comment]
If you have troubles when changing the DNS, the only solution right now is modifying the hosts file. 

On macOS they have DnsMasq to proxy all requests on the `*.test` domain, but for Windows the only good alternative I've found was [Acrylic DNS](http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome), that requires modifying the DNS.

**Comment by delta1186** [comment]
Go to C:\Users\username\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\acrylic
and open the AcrylicConfiguration.ini file.  Add your DNS server IP to line 12 under PrimaryServerAddress=x.x.x.x 

We have 2 DNS servers, but I am only using one and it works fine.  Then under my NIC properties, I set 127.0.0.1 as the primary and I will have my two internal DNS server IPs after that.  All internal DNS addresses can then be reached.

**Comment by LarBearrr** [comment]
Interesting. So in my case, running `ipconfig /all` lists my two corporate dns servers:
10.1.10.2
10.2.10.2

So I would update the file you mentioned to:
PrimaryServerAddress=10.1.10.2
SecondaryServerAddress=10.2.10.2

And then set the primary DNS under network adaptor settings to 127.0.0.1?

**Comment by delta1186** [comment]
That's correct.  I have a static IP assigned on my PC.  I ended up leaving my internal dns servers on my NIC config, just added the 127.0.0.1 and moved it to the first in the list:
127.0.0.1
10.0.10.1
10.0.10.2

**Comment by LarBearrr** [comment]
So simple! I can't believe I didn't think of this. Not sure how many people are working in a similar environment, but this was really helpful for me. Maybe it would be worth adding a note in the documentation about configuring DNS. Thanks @delta1186 !
