### ISSUE TITLE
Slow performance - TTFB up to 60

### ISSUE THREAD

**Issue by bonovski** [cretueusebiu/valet-windows#106]
I have a few wordpress sites that connect to a remote mysql DB.

The problem is that php/nginx performance is extremely slow, TTFB takes usually more than 20 seconds, but after that the site loads normally.

Anybody encountered similar issues?

WIN10, php7.2, mariadb 5.6 on remote server

**Comment by cretueusebiu** [comment]
Could be from the remote database. Try with a local one.

**Comment by staabm** [comment]
You could try running a profiler to measure whats slow (blackfire or xdebug or similar)

**Comment by bonovski** [comment]
Remote databases work fine when I use apache as the web server or when I use the original valet on macos.

I installed Laragon and response and loading times where the same as on macos/valet, but laragon has some other issues, so I don't want to use that.

It also works fine when I switch to the local db.

**Comment by bonovski** [comment]
Just booted up an ubuntu installation in virtualbox with "valet for linux" and it works as expected.

**Comment by bonovski** [comment]
Getting  some 10060 errors:

`2018/12/19 17:15:31 [error] 3240#6500: *4991 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "staging.test"`

**Comment by bonovski** [comment]
`fastcgi_buffering off` did the trick.

The solution is for WSL but works nevertheless.

https://stackoverflow.com/questions/46286420/php7-0-fpm-extremly-slow-on-ubuntu-windows-subsystem-linux

https://github.com/Microsoft/WSL/issues/2100

**Comment by LarBearrr** [comment]
Where did you change this setting at?

**Comment by bonovski** [comment]
> @bonovski Where did you change this setting at?

It's in `valet.conf`, I added it at the end of the php location block.
```
location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9001;
        fastcgi_index "C:/Users/USER/AppData/Roaming/Composer/vendor/cretueusebiu/valet-windows/server.php";
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME "C:/Users/USER/AppData/Roaming/Composer/vendor/cretueusebiu/valet-windows/server.php";
        fastcgi_param HOME "C:/Users/USER";
	fastcgi_buffering off;
    }
```

The file is located in `C:\Users\USER\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx\valet`

**Comment by LarBearrr** [comment]
Thanks so much! I had been looking in the wrong folder. Do you think running MAMP with Apache on port 8890 is affecting my response time?

**Comment by bonovski** [comment]
I don't think so, but nginx on windows can be finicky.
Additionally to turning `fastcgi_buffering off` I also installed non-thread-safe php.

I didn't notice any difference but it was recommended on the forums for nginx.

**Comment by darrylmorley** [comment]
I'm struggling with very slow performance in Windows, I've added fastcgi_buffering off; but it doesn't appear to have had any effect. Is there anything else I can try please?

**Comment by bonovski** [comment]
You can try adding `fastcgi_keep_conn on;` below too.
That's as fast as it gets.

**Comment by darrylmorley** [comment]
Thanks, i'll give it a shot.
