### ISSUE TITLE
Possible to update Acrylic DNS?

### ISSUE THREAD

**Issue by jamieburchell** [cretueusebiu/valet-windows#107]
I noticed when troubleshooting an issue with some external websites not loading while Acrylic DNS was enabled that there's a newer version (0.9.39). This version seems to have a GUI where you can clear the cache and edit the config files; it also removes some redundant stuff. I went to update then realised that this project includes it and installs/configures it.

The issues I experienced were some websites being inaccessible/bad SSL certificates or websites loading with assets missing. Not sure if an update would resolve, but it would be nice to be able to update it.

**Comment by bgallagh3r** [comment]
👍

I came here as I had a similar issue.  I was having problems loading some websites, one in particular was not loading at all.  It appears Acrylic was the culprit.  I had to manually disable the IP4/IP6 adapter settings to access the site.

**Comment by cretueusebiu** [comment]
I'll release a new version this weekend. There are few things behind that need to be updated, including Acrylic.

**Comment by bgallagh3r** [comment]
Wondering when this is going to get updated.

**Comment by cretueusebiu** [comment]
Updated in the latest release [2.1.0](https://github.com/cretueusebiu/valet-windows/releases/tag/2.1.0).
