### ISSUE TITLE
valet unlink nor working

### ISSUE THREAD

**Issue by csesumonpro** [cretueusebiu/valet-windows#109]
valet unlink nor working.   I have already apply many system for unlink  in two pc but not working.

1. firstly try to unlink command from comand promt normal mode => valet unlink my_project_name
2. second run comand promt administrator mode the run this command => valet unlink my_project_name
3. try to normal and administrative mode under project directory use this command => valet unlink my_project_name 

bit not work................??? Please solve it ASAP.

**Comment by sehmbimanvir** [comment]
@csesumonpro **valet unlink** not works for me also. So, currently i am unlink this in in following way.

- Navigate to **C:\Users\Username\.valet\Sites** 
- Delete specific site shortcut that you want to unlink.

**Comment by VincentKos** [comment]
can you give the name of your project ? Everything work here

**Comment by cretueusebiu** [comment]
Please try the latest release [2.1.0](https://github.com/cretueusebiu/valet-windows/releases/tag/2.1.0).

**Comment by banuaraidi** [comment]
still happend on ver 2.1, seem problem on isLink function

**Comment by Ahmed-Aboud** [comment]
you might also find the folder in 
`C:\Users\Username\.config\valet\Sites`

**Comment by buczoprazy** [comment]
Do not work on windows 10 latest release on November 2020

**Comment by muath-ye** [comment]
You need to stop valet and rename the folder and then unlink the site outside the path of the site with following command

> valet unlink YourSiteName
