### ISSUE TITLE
XAMPP now broken

### ISSUE THREAD

**Issue by jeremy-wgd** [cretueusebiu/valet-windows#110]
Hello

I installed valet, but now trying to go back to XAMPP I get this:

17:26:20  [Apache] 	Port 80 in use by "Unable to open process" with PID 6252!
17:26:20  [Apache] 	Apache WILL NOT start without the configured ports free!
17:26:20  [Apache] 	You need to uninstall/disable/reconfigure the blocking application
17:26:20  [Apache] 	or reconfigure Apache and the Control Panel to listen on a different port

I did valet uninstall, and it said it had uninstalled, but still I can't run XAMPP

Also if I type valet at the command prompt I get:  Laravel Valet for Windows 2.0.15

Which is weird since it should be uninstalled

If I type valet start I get: Could not start the phpfpmservice service. Check ~/.valet/Log for errors.

Any ideas how to get XAMPP running again?

Cheers!

**Comment by cretueusebiu** [comment]
To uninstall it you have to run the following commands as administrator:

```
valet stop
valet uninstall
composer global remove cretueusebiu/valet-windows
```

**Comment by jeremy-wgd** [comment]
Great. Thank for for a fast response, that's working now!

**Comment by inderaja** [comment]
Hello @cretueusebiu i accidentally delete the installed valet folder, then how i can stop the valet services running in port 80? Thanks!

**Comment by cretueusebiu** [comment]
@inderaja  Open Windows Services and look for  `Acrylic DNS Proxy` , `valet_nginx`, `valet_phpcgi` and `valet_phpcgi_xdebug` . Right click on them > Properties > Startup type: Disabled  + Stop and click Apply. Then make sure to also delete the Valet config files from `~/.config/valet`

**Comment by inderaja** [comment]
@cretueusebiu where is the valet directory ? and how can i delete those services ?

**Comment by cretueusebiu** [comment]
Once the services are stopped and disabled if you delete the Services folder from Valet, the next time you restart/shutdown the system they should be gone.

![Screenshot_1](https://user-images.githubusercontent.com/1517945/125966987-1be61ef0-d232-4e18-b3d8-f5ad1f49f7ed.png)

**Comment by inderaja** [comment]
@cretueusebiu Thankyou, it works!

**Comment by satryandi** [comment]
> To uninstall it you have to run the following commands as administrator:
> 
> ```
> valet stop
> valet uninstall
> composer global remove cretueusebiu/valet-windows
> ```

file directory?
