### ISSUE TITLE
No Indicator for secured sites

### ISSUE THREAD

**Issue by sehmbimanvir** [cretueusebiu/valet-windows#111]
Hi,

There's a issue with ```valet links``` command. It doesn't display indicator for secured website.

![Command](https://user-images.githubusercontent.com/10684810/53678795-e9426580-3ce9-11e9-977e-a22c26d0de54.jpg)

This problem is due to the following code.

```
protected function getCertificates($path)
    {
        return collect($this->files->scanDir($path))->filter(function ($value, $key) {
            return ends_with($value, '.crt');
        })->map(function ($cert) use ($length) {
            return substr($cert, 0, -8);
        })->flip(); 
}
```
I am using .test domain. So, In my case -8 refers to crt.test. But this needs to be referred as .crt.test. It means length will be -9 instead of -8. One can also use domain length as dynamic variable. By Following Code.

```
$length = strlen('.crt.' . $this->config->read()['domain']);
```

So, Updated code will be

```
protected function getCertificates($path)
    {
        $length = strlen('.crt.' . $this->config->read()['domain']);
        return collect($this->files->scanDir($path))->filter(function ($value, $key) {
            return ends_with($value, '.crt');
        })->map(function ($cert) use ($length) {
            return substr($cert, 0, -$length);
        })->flip();
    }
```
![new](https://user-images.githubusercontent.com/10684810/53678929-a5e8f680-3ceb-11e9-97ef-e911cf42d000.jpg)

**Comment by cretueusebiu** [comment]
Fixed in the latest release [2.1.0](https://github.com/cretueusebiu/valet-windows/releases/tag/2.1.0).
