### ISSUE TITLE
Windows 10 "valet install", "valet stop" valet uninstall"  not working.  Breaks XAMPP

### ISSUE THREAD

**Issue by dakicks87** [cretueusebiu/valet-windows#116]
Hello, I am having multiple  problems with valet-windows.
On Windows 10 using PowerShell `valet install` does not work. 
I get message : 

> valet : The term 'valet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I have also tried running to command from where valet is installed `C:\Users\Michael\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows`

I have then tried using XAMPP, but my local host is being blocked by Valet. So now I don't have a local dev environment working.

I have tried to uninstall it by the commands `valet stop` and  `valet uninstall` but i get same error message as above.

What can i do to install valet and what can I do to uninstall it?

**Comment by cretueusebiu** [comment]
How did you manage to install it in the first place if the `valet` command doesn't work ? 
Make sure that you have the composer path added to your env variable.

If you din't install it, just rune `composer global remove cretueusebiu/valet-windows` and the package should be removed.
