### ISSUE TITLE
Valet on Windows 10 Issue

### ISSUE THREAD

**Issue by Unstinted** [cretueusebiu/valet-windows#124]
I installed valet-windows but when i run valet start, i can ping the address of the app in cmd line but the url is displaying NOT FOUND on browser. Kindly help with a solution.

**Comment by agiorgini** [comment]
same here, any solution found?

**Comment by odaiderawi** [comment]
same with me

**Comment by jasperf** [comment]
Did anyone here check the logs to see if there were any particular Nginx error or access logs? Did it register the 404 error or not?

**Comment by malpaso** [comment]
Getting the same issue. Nginx is running, Valet is running, AcrylicDNS is running, PHP is running. There is only one error I can see in the **nginxservice.wrapper.log**
`2020-11-26 21:19:03,563 FATAL - WMI Operation failure: ServiceCannotAcceptControl
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)`
