### ISSUE TITLE
Windows 10 reports as offline (is online)

### ISSUE THREAD

**Issue by alystair** [cretueusebiu/valet-windows#125]
After setting the adapter to use Acrylic, Windows 10 reports that it is offline - even though almost everything works... OneDrive and Office report as offline and can no longer save items to the cloud unless I remove the DNS setting.

**Comment by ryangurn** [comment]
Ive been having a similar issue. I was forced to remove the DNS setting. This is currently on windows 10 pro.

**Comment by wisegear** [comment]
Have you added a secondary DNS?  Set preferred DNS server to 127.0.01 and the Alternative DNS server to 8.8.8.8

**Comment by ryangurn** [comment]
let me give it a shot, I attempted to reinstall the entire package since I recently updated and that broke things.

**Comment by ryangurn** [comment]
![Capture](https://user-images.githubusercontent.com/1297082/67149856-4719c280-f265-11e9-8d4d-dbb35091c9ef.PNG)
 Still not working

**Comment by wisegear** [comment]
Is your internet connection showing as active or unable to connect?  Are you using Wi-FI?

**Comment by Abdelraman** [comment]
Same here using wifi

**Comment by mbardelmeijer** [comment]
Have the same issue on a WiFi connection.

**Comment by mbardelmeijer** [comment]
Seems to be that Acrylic binds to 0.0.0.0, but the Windows service ICS (Internet Connection Sharing). When binding it to 127.0.0.1 in the config it seems to be working fine.

Got this on WiFi but also on a wired connection.

**Comment by weerdenburg** [comment]
I just did a `composer global update` on my Windows 10 machine and now Acrylic is also not working :-(

For every local site that I try to open I get ERR_CONNECTION_REFUSED

@mbardelmeijer did you find a way to configure it and make it work again?
Could you please explain what you have changed?

**Comment by weerdenburg** [comment]
My problems where different, in the Windows services list Acrylic was added twice!
I think the name of the service was changed between two versions and it tried to start up two times, I removed de old one using regedit.

I'm still having issues with ERR_CONNECTION_REFUSED, but I think that's another issue. The DNS of *.test domains now correctly resolve to 127.0.0.1

**Comment by mbardelmeijer** [comment]
@weerdenburg i've changed the setting `LocalIPv4BindingAddress` from `0.0.0.0` to: `LocalIPv4BindingAddress=127.0.0.1`

Have to say, i'm not using Valet for Windows at the moment (using WSL2 /w Acrylic) but the issue seems to be the same.

**Comment by alystair** [comment]
@mbardelmeijer curious about your WSL2 setup - do you have a write up anywhere, or 3rd party tutorial?

**Comment by mbardelmeijer** [comment]
@alystair not at the moment sorry. 

I'm using Windows Insider Slow Ring to enable WSL2 support, and installed it like a server (nginx, php-fpm etc.). Then poining `*.test` to 127.0.0.1 with Acrylic. nginx handles that request through php-fpm and serves the website. phpstorm is connected to a mount to the WSL environment.

Not perfect by any means, are some issues with it but in general i'm happy with the setup.

I'll post something here if i ever write something up on it.

**Comment by ryangurn** [comment]
So upon having this exact issue I have concluded a couple of things when I finally got things fixed. 
1. Ensure that your windows hosts file has the following line in it `127.0.0.1 *.test`
2. Ensure that you open the acrylic hosts configuration file and check for a line that looks something like `127.0.0.1 >test`, and if it does not then add it in.
3. Ensure that you open the acrylic configuration file and like @mbardelmeijer said to ensure that you change `LocalIPv4BindingAddress` from `0.0.0.0` to `LocalIPv4BindingAddress=127.0.0.1`.
4. Make sure that the DNS configurations are set up correctly within the windows settings area. 

Thanks for all the help and its finally working again after months.

**Comment by alystair** [comment]
@ryangurn thanks for that Ryan! I'm thinking it might be useful to additionally change LocalIPv6BindingAddress to `0:0:0:0:0:0:0:1` local loopback?

@cretueusebiu do you think these changes could be bundled in the next release? At least the acrylic host configs

**Comment by mbardelmeijer** [comment]
@alystair as promised, have written up some info about our WSL setup: https://github.com/enflow-nl/wsl2-php-development

**Comment by alystair** [comment]
Wow you rock @mbardelmeijer thanks!
