### ISSUE TITLE
Valet commands is not working from c drive

### ISSUE THREAD

**Issue by KaziJahurul** [cretueusebiu/valet-windows#126]
I have installed the valet for windows successfully and parked it in user/documents/projects folder. I have created a project called abic and when I type abic.test in browser it is working too. But after restarting my computer none of the valet command is working from Poweshell. here is a screenshot: https://prnt.sc/pha4g3 Please check this screenshot and let me know what I am doing wrong.

Thanks in advance.

**Comment by bdunnaway** [comment]
It seems composer changed where it kept its config files on my machine.  I had to add the new bin directory to my system PATH variable.
Like this:
C:\Users\{{YOUR USERNAME}}\AppData\Roaming\Composer\vendor\bin
