### ISSUE TITLE
How to make general usage faster?

### ISSUE THREAD

**Issue by ChampRay** [cretueusebiu/valet-windows#127]
I know when running my own local Ubuntu server through WSL installed with NGINX, PHP-FPM and symlinking my project, my page loads much faster compared to valet-windows. Is there a way to make valet-windows perform better like Ubuntu WSL?

I use Windows 10.

**Comment by EmilMoe** [comment]
I didn't do the Acrylic DNS, but instead I add my domains (project.test) to my hosts file (on Windows) and it seems to be fast. I add them to the top, to make sure they match faster (if it makes any difference - I don't know for sure).

```
127.0.0.1 project.test
````

**Comment by cretueusebiu** [comment]
Adding the domains in your hosts files should make it faster than Acrylic DNS. But it's really that slow for you ?

**Comment by ChampRay** [comment]
Oh yeah, I didn't even use Acrylic DNS. I was using my host file. It was very slow, I am using Docker now and its tremendously faster. It matters in bigger projects.

**Comment by bonovski** [comment]
I have all three valet "versions" installed and use them regularly.
I usually get the fastest experience on ubuntu, especially when using a big wordpress site and when using a remote database. A tad slower is macos and  last by quite a margin is the performance on windows. 
IMHO that is the fault of nginx (already posted some settings here to speed it up a bit).
Why?
Using WAMP I get comparable performance to ubuntu and macos but apache can't handle multiple remote db connections correctly so using WAMP is not an option for me.

**Comment by ChampRay** [comment]
Yeah, you're better off just using Docker for Windows. While I appreciate this project, it just doesn't seem to be used enough to get the proper updates it needs.
