### ISSUE TITLE
laravel passport incompatiblity issue

### ISSUE THREAD

**Issue by iteniasim** [cretueusebiu/valet-windows#129]
i have a project with working spa backend served in laragon which uses apache server, but when i use this valet to serve the backend it does get served but the laravel passport portion in particular doesn't work, i could not find any error per se, but it just gets stuck trying to return the token and times out.

passport version is 7.2.2

**Comment by cretueusebiu** [comment]
Fixed in [2.1.3](https://github.com/cretueusebiu/valet-windows/releases/tag/2.1.3).
