### ISSUE TITLE
Undefined function mysql_connect()... Fatal error installing Wordpress on Valet 

### ISSUE THREAD

**Issue by concypt** [cretueusebiu/valet-windows#135]
PHP 7.3.16
MariaDB 10.4
Wordpress 5.3.2 

Error is: 
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\projects\applications\taleem\wp-includes\wp-db.php:1665 Stack trace: #0 C:\projects\applications\taleem\wp-includes\wp-db.php(632): wpdb->db_connect() #1 C:\projects\applications\taleem\wp-includes\load.php(425): wpdb->__construct('root', '', 'db_taleem', 'localhost') #2 C:\projects\applications\taleem\wp-settings.php(116): require_wp_db() #3 C:\projects\applications\taleem\wp-config.php(90): require_once('C:\\projects\\app...') #4 C:\projects\applications\taleem\wp-load.php(37): require_once('C:\\projects\\app...') #5 C:\projects\applications\taleem\wp-blog-header.php(13): require_once('C:\\projects\\app...') #6 C:\projects\applications\taleem\index.php(17): require('C:\\projects\\app...') #7 C:\Users\imran\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\server.php(143): require('C:\\projects\\app...') #8 {main} thrown in C:\projects\applications\taleem\wp-includes\wp-db.php on line 1665

Fatal error: Uncaught Error: Call to undefined function wp_kses_normalize_entities() in C:\projects\applications\taleem\wp-includes\formatting.php:4316 Stack trace: #0 C:\projects\applications\taleem\wp-includes\class-wp-fatal-error-handler.php(190): esc_url('https://wordpre...') #1 C:\projects\applications\taleem\wp-includes\class-wp-fatal-error-handler.php(147): WP_Fatal_Error_Handler->display_default_error_template(Array, false) #2 C:\projects\applications\taleem\wp-includes\class-wp-fatal-error-handler.php(52): WP_Fatal_Error_Handler->display_error_template(Array, false) #3 [internal function]: WP_Fatal_Error_Handler->handle() #4 {main} thrown in C:\projects\applications\taleem\wp-includes\formatting.php on line 4316

**Comment by cretueusebiu** [comment]
[mysql_connect](https://www.php.net/manual/en/function.mysql-connect.php) has been removed from PHP 7.
