### ISSUE TITLE
Version 2.1.2 reports as version 2.1.1

### ISSUE THREAD

**Issue by alystair** [cretueusebiu/valet-windows#137]
https://github.com/cretueusebiu/valet-windows/blob/d58836a265b4b165913c794e3c8a435ada1b2bc1/cli/valet.php#L35

Forgot to bump to 2.1.2 ... 

So -V and 'on-latest-version' are borked.

**Comment by cretueusebiu** [comment]
Fixed in [2.1.3](https://github.com/cretueusebiu/valet-windows/releases/tag/2.1.3).
