### ISSUE TITLE
page can't be reached | IP address couldn't be found

### ISSUE THREAD

**Issue by abdhannan** [cretueusebiu/valet-windows#141]
I don't know what is the issue here.

yesterday my valet was work perfectly, but, the problem comes after windows update (Fuck you windows that force shutdown my laptop).
I always got the page reached. I know the problem occurs after I changed the DNS from the network.

I git frustrated, My laravel 70% complete.

Is there anyone can help me here? what wrong with this?

**Comment by AndrewMast** [comment]
I also hate forced windows updates. Ugh.

My guess is that the update reset the DNS network settings or messed up valet services. Did you verify that the Internet Protocol is set to `127.0.0.1` for Version 4 and `::1` for Version 6? I would also try to run `valet install` again in powershell

**Comment by rhonivanpareja** [comment]
having the same issue here. all of my settings are as is.
