### ISSUE TITLE
Docker and Acrylic DNS

### ISSUE THREAD

**Issue by delta1186** [cretueusebiu/valet-windows#143]
I was playing around with Docker containers the other week and ran into an issue with I believe Acrylic DNS.  

I used Docker to setup a mysql instance and everything appeared to be working fine.  I was able to connect to the database.  Then I tried to link it up to a test laravel app.  That's when I realized that I could no longer hit my .test domains.  

Just curious if anyone else using docker has experienced this.  I am hoping it is just some additional config that I need to set in the AcylicConfiguration.ini file.  I currently set the PrimaryServerAddress and SecondaryServerAddress to my internal domain DNS servers.  Additionally, I add a wildcard entry in the [CacheExceptionsSection] for my internal domain.

Pretty sure it is related to Acrylic and Docker.  If shutdown docker and reboot, valet .test domains will work again. However, if I startup docker again they will stop working.

I am hoping to get this figured out some that I can use the new takeout tool by Tighten if I gets ported for windows.

**Comment by tomwignall** [comment]
I don't this is a fault of Valet for windows though??

**Comment by ptournet** [comment]
Docker and Acrylic are both competing to use port 53 (DNS)... Depending on which runs first the other one can't run properly (or even crashes) ! The only solution I'm seeing would be to use a docker based DNS proxy instead of Acrylic to be able to use valet and docker at the same time... I'm gonna look into it as it bothers me a lot too !

**Comment by delta1186** [comment]
I messed around with this more Monday and reached the same conclusion. I will tinker on using a docker dns container too. If I get something working I'll post back here.

**Comment by delta1186** [comment]
@ptournet so I did a thing.  https://hub.docker.com/r/hickskp/docker-dns  
More to come hopefully soon!
