### ISSUE TITLE
Valet couldn't connect if no internet

### ISSUE THREAD

**Issue by sufita** [cretueusebiu/valet-windows#15]
Did any step I miss from the installation or maybe by default this will not work if no internet ?

**Comment by cretueusebiu** [comment]
After you install it it should work without internet. Does it work with internet ?

**Comment by sufita** [comment]
Yes, it does. I can't reach the page if it were offline. It just work  with internet connection (WIFI).

**Comment by cretueusebiu** [comment]
I guess it has to do with the [Acrylic DNS Proxy](https://github.com/cretueusebiu/valet-windows/tree/master/bin/acrylic). This proxies all requests on the *.dev domain to `127.0.0.1`. 

What you can do is add manually each domain to the `C:/Windows/System32/drivers/etc/hosts` file.

**Comment by sufita** [comment]
Thanks.
