### ISSUE TITLE
how to uninstall php?

### ISSUE THREAD

**Issue by goldcoders** [cretueusebiu/valet-windows#154]
I have a problem i cannot uninstall php, 
I simple cannot remove it from C:\php
when i look at task manager php cgi is running 4 process but everytime i kill it it just respawn

Any work around on how to kill that process , since its locking windows from deleting the php folder

**Comment by cretueusebiu** [comment]
Run `valet uninstall` as administrator and then delete PHP..

**Comment by goldcoders** [comment]
I already valet uninstall. The problem is the php folder is undeletable because it is running on start up automatically
php-fpm-cgi which you if u trie to end task or kill it on task manager it wont. 

so my resolve was to use unlocker and unlocker the folder of php , then after that i can kill the process
then delete the whole php folder.
