### ISSUE TITLE
windows terminal issue ... with valet... process exited with code 4294967295

### ISSUE THREAD

**Issue by goldcoders** [cretueusebiu/valet-windows#158]
suprisingly all i can remember prior my wsl arch command has this

```
Error: 0xffffffff

[process exited with code 4294967295]
```
is i dont have valet-windows

i thought windows updates causes issue to have that

but after i run valet stop

and run `arch` on powershell that error disappeared

Any reason for this? 

I read many errors about it
https://github.com/microsoft/WSL/issues/5092

their solution is running this command but it wont work `netsh winsock reset`

As i wrapped my head around the only way to make valet works is everytime you restart windows
you valet stop
then run wsl 
then do valet start

I hope there will be a better solution on this.

**Comment by cretueusebiu** [comment]
This is related to this issue https://github.com/microsoft/WSL/issues/4929.
You have to run `valet stop` start a WSL terminal then run `valet start`.

**Comment by goldcoders** [comment]
The Only Solution I come up is Disabled 
Acrylic on start up , sames goes to all valet services
such as nginx php-fpm and php-cpi.

I thinks its better to run valet start every now and then when i only need that instance...

I totally remember my setup in archlinux
where i also disabled it using systemctl commands

also invoke it manually when i needed it.

My main take away on this is That WSL i think is loaded after all the DNS configuration happened.

I dont know how to re arrange the priority of services to be run on windows, 

So i think , my solution is Good for now. 
Unless otherwise someone fix this error on both the acrylic and wsl ....

**Comment by goldcoders** [comment]
Disabling services on windows , just type services on you window search 
first app that appear  will list all your automatic services running on startup.

I just change acrylic, and valet services to manual...

restart pc, then 

everytime you need valet ,
just run valet start
