### ISSUE TITLE
valet_phpcgi not started

### ISSUE THREAD

**Issue by subhadipghorui** [cretueusebiu/valet-windows#162]
valet_phpcgi not started.
How to fix that. Run valet restart multiple time not working
![image](https://user-images.githubusercontent.com/49529825/106188019-6d4e4200-61cc-11eb-9046-dda8e165f5a9.png)

![image](https://user-images.githubusercontent.com/49529825/106188071-7fc87b80-61cc-11eb-8a65-6936ad53bce3.png)

I install this library on vwware win10 machin its work there but not in main machine.

**Comment by cretueusebiu** [comment]
Try checking the logs in `~/.config/valet/Log`

**Comment by subhadipghorui** [comment]
I solved this after spending a lot. The problem was the PHP service was not running.
![image](https://user-images.githubusercontent.com/49529825/106236862-af56a280-6223-11eb-93cb-7d5b8da20086.png)

I was using xampp. So I have to change the apache server port from 80 to 81. Then to solve this problem you have to change valet_phpcgi port from default 9001 to another(ex- 9002).

Go to **_C:\Users\Super Admin\.config\valet directory_** and edit config.json file. Change-
"php_port": 9002

Then **uninstall** valet and (do not remove anything). Just **reinstall** it.
It will work.
