### ISSUE TITLE
Valet can't install if  %USERPROFILE% value contains a space

### ISSUE THREAD

**Issue by navaneeth-raman-bhaskar** [cretueusebiu/valet-windows#170]
when try to run `valet install`  cmd throws an error ` Failed to install service [phpcgiservice]. Check ~/.config/valet/Log for errors.                                      
 'C:/Users/Navaneeth' is not recognized as an internal or external command,                                            
  operable program or batch file. `

My  %USERPROFILE% value was **Navaneeth Raman Bhaskar**

**Comment by cretueusebiu** [comment]
The latest release should fix this issue
https://github.com/cretueusebiu/valet-windows/releases/tag/2.3.2

**Comment by navaneeth-raman-bhaskar** [comment]
Thanks for the update it's working.
