### ISSUE TITLE
When valet stopped I cannot connect to any website Win10

### ISSUE THREAD

**Issue by halilcakar** [cretueusebiu/valet-windows#171]
So first of all hi and thanks for creating this!!

I've just found it and tried which is perfectly working with making Acrylic DNS Proxy settings for windows 10. (Giving IPV4 and IPv6 to default DNS Servers).

But after I saw that it's kinda working with quite lots of process power I though "Okey since I'm not gonna work right now lets stop the valet" so I stopped it with `valet stop`.

After this with Acrylic DNS settings, it started telling me it cannot connect to websites and practicly anything. 

So I reverted DNS settings to automatic and it started connecting again.. An go on like this.

Is there a solution for this problem or am I doing something wrong? :)

My system is Win 10 Pro - Version 21H1 - Build 19043.985

**Comment by cretueusebiu** [comment]
You can limit the number of PHP processes from 4 to 1 by editing `~/.config/valet/Services/phpcgiservice.xml`:

```xml
<env name="PHP_FCGI_CHILDREN" value="1"/>
```
Then run `valet restart`.

You can also run `valet stop php-xdebug` to stop an extra PHP process used for xdebug.

I'm on Win 10 20H2 so for me if I stop valet I don't have any problem connecting to websites. I'll see what happens once I get the latest update.

**Comment by halilcakar** [comment]
Thank you for your quick answer.

About the issue,
When I just configure IPv6 and not IPv4 it's still working as expected and when I stop the valet it keeps working I actually didn't understand why but it's kinda fixed my problem.


On the other hand...
I've tried the env value to 1 and here is some screenshots:

This was I guess always one :)
![image](https://user-images.githubusercontent.com/18047554/121132645-0e639e00-c83a-11eb-9ffa-d8fb8d5e0dad.png)

After stopping `php-xdebug` it actually went down from 4 instances to 2 instances.
![image](https://user-images.githubusercontent.com/18047554/121132679-1b808d00-c83a-11eb-93b9-6eae6bb80b73.png)

The point I dont understan why there are 13 instances of nginx.exe :D
![image](https://user-images.githubusercontent.com/18047554/121132718-2a673f80-c83a-11eb-94f8-d2bef5be41c7.png)

Again thank you for your help, even with this I would be okey actually So the pictures and question was just because I kinda get curios about it :)

**Comment by cretueusebiu** [comment]
The number of Nginx processes is controlled by the [worker_processes](https://nginx.org/en/docs/ngx_core_module.html#worker_processes) directive. When set to `auto` it will be equal to the number of CPU cores + 1.

You can set it to a specific number in:
 `C:/Users/YOUR_USERNAME/AppData/Roaming/Composer/vendor/cretueusebiu/valet-windows/bin/nginx/conf/nginx.conf`
then `valet restart`.

**Comment by halilcakar** [comment]
Thank you again for your help.

One last question if you can answer when you have time.

Is it possible to add mysql and phpmyadmin into this system? What whould you thing about it? :)

**Comment by cretueusebiu** [comment]
Adding more to it makes it harder to maintain. 
If you're just building simple apps you can just use SQLite for your local development.

**Comment by halilcakar** [comment]
> Adding more to it makes it harder to maintain.
> If you're just building simple apps you can just use SQLite for your local development.

I'll look for another solution again thank you soo much for your help 🙏
