### ISSUE TITLE
Looks like valet share is broken?

### ISSUE THREAD

**Issue by LewisLarsen** [cretueusebiu/valet-windows#176]
The command `valet ngrok authtoken <token>` does store the authtoken in the .ngrok2/ngrok.yml file however valet will always prompt you to set the token. 

Have tried running an elevated Microsoft Terminal window as well to no avail.

```
PS C:\Users\larsen\sites\x> valet ngrok authtoken <token>
Authtoken saved to configuration file: C:\Users\larsen/.ngrok2/ngrok.yml

PS C:\Users\larsen\sites\x> valet share
Forwarding to local port 443 or a local https:// URL is only available after you sign up.
Sign up at: https://ngrok.com/signup
Then use: valet ngrok authtoken my-token
```

**Comment by adgower** [comment]
> The command `valet ngrok authtoken <token>` does store the authtoken in the .ngrok2/ngrok.yml file however valet will always prompt you to set the token.
> 
> Have tried running an elevated Microsoft Terminal window as well to no avail.
> 
> ```
> PS C:\Users\larsen\sites\x> valet ngrok authtoken <token>
> Authtoken saved to configuration file: C:\Users\larsen/.ngrok2/ngrok.yml
> 
> PS C:\Users\larsen\sites\x> valet share
> Forwarding to local port 443 or a local https:// URL is only available after you sign up.
> Sign up at: https://ngrok.com/signup
> Then use: valet ngrok authtoken my-token
> ```

same problem.

**Comment by cretueusebiu** [comment]
Strange... seems to work for me.

**Comment by adgower** [comment]
> Strange... seems to work for me.

are you using with sites you have set valet secure on?

**Comment by halilcakar** [comment]
Is there any updates on this. My app already unsecure and when I run `valet share` it's just opening a console to start ngrok and cmd closes.

**Comment by cretueusebiu** [comment]
Should be fixed in 2.4.1.

**Comment by michaelmannucci** [comment]
> Is there any updates on this. My app already unsecure and when I run `valet share` it's just opening a console to start ngrok and cmd closes.

I have this same issues. When I do `valet share1, cmd opens for less than a second and closes.

Any ideas what I could be doing wrong?

**Comment by michaelmannucci** [comment]
> > Is there any updates on this. My app already unsecure and when I run `valet share` it's just opening a console to start ngrok and cmd closes.
> 
> I have this same issues. When I do `valet share1, cmd opens for less than a second and closes.
> 
> Any ideas what I could be doing wrong?

Figured it out... I forgot to validate my email account with Ngrok! Big fail.
