### ISSUE TITLE
Could not start the phpfpmservice service. Check ~/.valet/Log for errors.

### ISSUE THREAD

**Issue by Pioruniasty** [cretueusebiu/valet-windows#19]
Hi, 

Today I decided to install Valet on Windows 10. I got this error:

```
Could not start the phpfpmservice service. Check ~/.valet/Log for errors.
```

~/.valet/Log has file nginx-error which is empty. I tried to run ``valet start`` with admin privilages but I get same error.

**Comment by Pioruniasty** [comment]
Ok I found that I had ran PHP Server via "php" command but I have one more q: after ``valet install`` & ``valet start`` & ``valet park`` in my folder where is for ex. laravel project named ``example`` when I go to ``example.dev`` I don't see anything but I gets error: ERR_ICANN_NAME_COLLISION

**Comment by cretueusebiu** [comment]
Try `valet domain app` and use `example.app`.

**Comment by cretueusebiu** [comment]
Also check if Acrylic DNS is configured http://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration . By default is configured when you install Valet, but sometime it reverts back.

**Comment by codeitlikemiley** [comment]
i got same issue im using windows 10, and using CMD terminal

**Comment by nanadjei2** [comment]
Me too. It was working fine with internet. But I get the same error once I don't have internet access. Am using windows 10

**Comment by Almusamim** [comment]
Got same error
`Could not start the phpfpmservice service. Check ~/.valet/Log for errors. `

**Comment by karlkras** [comment]
Same problem... nothing in the logs.

**Comment by abrhambas01** [comment]
I encountered mine because I've installed a software that disabled some startup services.

**Comment by diannurdiana86** [comment]
run cmd as administrator
valet install or valet start

**Comment by laurensiusadi** [comment]
I'm running Git Bash on Windows as administrator,
but it was running on my D:/project-folder
I changed to C:/
Then `valet start` runs with no problem
