### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by yuditia** [cretueusebiu/valet-windows#190]
![image](https://user-images.githubusercontent.com/68840381/150312761-564e5371-2106-4dfa-b41b-70c37dddf7fb.png)

why valet not working,
i use php v.8 and win 7
i already set dns

**Comment by ponchacc** [comment]
as you mention above you may valet park the "appliction" folder, not the "coba-laravel" 
do park appliction folder then try. 

Won't work offline then....>
You are offline so you may try this (worked for me):

(Edit Windows Host file) 

Step - 1: (if you very beginner)
> Open Notepad as Administrator
> Ctrl + O  (Open File)
> C:\Windows\System32\drivers\etc
> file type (All File (*.*))   { Toggle Text Documents (*.txt) to All File (*.*) }
> Select hosts and click open

Step - 2: (if you very beginner)
> 127.0.0.1  yourdomain.test
   127.0.0.1  www.yourdomain.test

{edit every time as run new domain}

view this https://youtu.be/faoyxBJQerU    (N.B. not promoted).

Please know if work. 

Thanks All.
