### ISSUE TITLE
Install of cretueusebiu/valet-windows failed

### ISSUE THREAD

**Issue by amaliakivansa** [cretueusebiu/valet-windows#191]
i tried to install cretueusebiu/valet-windows, but i found the error like this :

Running composer update cretueusebiu/valet-windows Loading composer repositories with package information Updating dependencies Lock file operations: 24 installs, 0 updates, 0 removals

Locking cretueusebiu/valet-windows (2.4.1)
Locking illuminate/collections (v8.81.0)
Locking illuminate/container (v8.81.0)
Locking illuminate/contracts (v8.81.0)
Locking illuminate/macroable (v8.81.0)
Locking mnapoli/silly (1.7.3)
Locking nategood/httpful (0.3.2)
Locking paragonie/constant_time_encoding (v2.5.0)
Locking paragonie/random_compat (v9.99.100)
Locking php-di/invoker (2.3.3)
Locking phpseclib/phpseclib (3.0.13)
Locking psr/container (1.1.2)
Locking psr/simple-cache (1.0.1)
Locking symfony/console (v5.4.3)
Locking symfony/deprecation-contracts (v2.5.0)
Locking symfony/polyfill-ctype (v1.24.0)
Locking symfony/polyfill-intl-grapheme (v1.24.0)
Locking symfony/polyfill-intl-normalizer (v1.24.0)
Locking symfony/polyfill-mbstring (v1.24.0)
Locking symfony/polyfill-php73 (v1.24.0)
Locking symfony/polyfill-php80 (v1.24.0)
Locking symfony/process (v5.4.3)
Locking symfony/service-contracts (v2.5.0)
Locking symfony/string (v5.4.3) Writing lock file Installing dependencies from lock file (including require-dev) Package operations: 24 installs, 0 updates, 0 removals
Downloading symfony/polyfill-php80 (v1.24.0)
Downloading symfony/process (v5.4.3)
Downloading paragonie/random_compat (v9.99.100)
Downloading paragonie/constant_time_encoding (v2.5.0)
Downloading phpseclib/phpseclib (3.0.13)
Downloading nategood/httpful (0.3.2)
Downloading symfony/polyfill-mbstring (v1.24.0)
Downloading symfony/polyfill-intl-normalizer (v1.24.0)
Downloading symfony/polyfill-intl-grapheme (v1.24.0)
Downloading symfony/polyfill-ctype (v1.24.0)
Downloading symfony/string (v5.4.3)
Downloading symfony/deprecation-contracts (v2.5.0)
Downloading psr/container (1.1.2)
Downloading symfony/service-contracts (v2.5.0)
Downloading symfony/polyfill-php73 (v1.24.0)
Downloading symfony/console (v5.4.3)
Downloading php-di/invoker (2.3.3)
Downloading mnapoli/silly (1.7.3)
Downloading psr/simple-cache (1.0.1)
Downloading illuminate/contracts (v8.81.0)
Downloading illuminate/container (v8.81.0)
Downloading illuminate/macroable (v8.81.0)
Downloading illuminate/collections (v8.81.0)
Downloading cretueusebiu/valet-windows (2.4.1)
Installing symfony/polyfill-php80 (v1.24.0): Extracting archive
Installing symfony/process (v5.4.3): Extracting archive
Installing paragonie/random_compat (v9.99.100): Extracting archive
Installing paragonie/constant_time_encoding (v2.5.0): Extracting archive
Installing phpseclib/phpseclib (3.0.13): Extracting archive
Installing nategood/httpful (0.3.2): Extracting archive
Installing symfony/polyfill-mbstring (v1.24.0): Extracting archive
Installing symfony/polyfill-intl-normalizer (v1.24.0): Extracting archive
Installing symfony/polyfill-intl-grapheme (v1.24.0): Extracting archive
Installing symfony/polyfill-ctype (v1.24.0): Extracting archive
Installing symfony/string (v5.4.3): Extracting archive
Installing symfony/deprecation-contracts (v2.5.0): Extracting archive
Installing psr/container (1.1.2): Extracting archive
Installing symfony/service-contracts (v2.5.0): Extracting archive
Installing symfony/polyfill-php73 (v1.24.0): Extracting archive
Installing symfony/console (v5.4.3): Extracting archive
Installing php-di/invoker (2.3.3): Extracting archive
Installing mnapoli/silly (1.7.3): Extracting archive
Installing psr/simple-cache (1.0.1): Extracting archive
Installing illuminate/contracts (v8.81.0): Extracting archive
Installing illuminate/container (v8.81.0): Extracting archive
Installing illuminate/macroable (v8.81.0): Extracting archive
Installing illuminate/collections (v8.81.0): Extracting archive
Installing cretueusebiu/valet-windows (2.4.1): Extracting archive Install of cretueusebiu/valet-windows failed 23/23 [============================] 100%
[RuntimeException] Could not delete C:\Users\Amalia\AppData\Roaming\Composer\vendor/cretueusebiu/valet-windows\bin\acrylic\AcrylicServ ice.exe: This can be due to an antivirus or the Windows Search Indexer locking the file while they are analyzed

i'm using windows 10 and i didn't know what exactly happen. thank you for your help

**Comment by razialfarabi** [comment]
try to uninstall composer first, then install again. Before installing again, first check the composer folder is still on ur computer or not. If it's still there, delete the composer folder. 

if the folder can't be deleted, check the taskbar and end task AcrylicService then try to delete the folder.

**Comment by amaliakivansa** [comment]
i have tried it & it worked! thank you so much!
