### ISSUE TITLE
An error arises when I try to install valet-windows

### ISSUE THREAD

**Issue by dev1662** [cretueusebiu/valet-windows#192]
- cretueusebiu/valet-windows[2.4.0, ..., 2.4.1] require symfony/process ^4.0|^5.0 -> found symfony/process[v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires cretueusebiu/valet-windows ^2.4 -> satisfiable by cretueusebiu/valet-windows[2.4.0, 2.4.1].

**Comment by Tomcatt1st** [comment]
try this command :

composer global require cretueusebiu/valet-windows -w

**Comment by dev1662** [comment]
> try this command :
> 
> composer global require cretueusebiu/valet-windows -w

ok
