### ISSUE TITLE
Disable auto start on boot

### ISSUE THREAD

**Issue by rognales** [cretueusebiu/valet-windows#196]
I'm not sure if this being asked before, but how do i turn off the start on boot? 

**Reason**: This is related to known issue of AcrylicDNS conflict with Docker Desktop. Its troublesome to stop valet, restart docker & finally start valet.

**Expectation**: I want to set Docker to start on boot and Valet to start on-demand.

**Comment by cretueusebiu** [comment]
I had the same problem, but you can just set the AcrylicDNS service startup type to Automatic (Delayed Start) and will start after Docker.

![Screenshot_1](https://user-images.githubusercontent.com/1517945/158453262-366160a7-4e78-446a-8911-84cb52133ba5.png)
.

**Comment by rognales** [comment]
That's a good workaround. That should do the tricks.
