### ISSUE TITLE
PHP install script error

### ISSUE THREAD

**Issue by Nulimitz** [cretueusebiu/valet-windows#202]
Installing php.ini...
Installing CA certificate...
Downloading Xdebug...
Could not find a Xdebug release for PHP 8.1.
At C:\Users\Marcus\AppData\Local\Temp\php.ps1:47 char:5
+     throw "Could not find a Xdebug release for PHP $phpVersion."
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...se for PHP 8.1.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find a Xdebug release for PHP 8.1.

**Comment by vdhruv** [comment]
Getting the same error.

**Comment by Nulimitz** [comment]
There is a work around. You can download a copy of the php_xdebug (https://odan.github.io/2020/12/03/xampp-xdebug-setup-php8.html) and save it in your php/ext folder. Make sure you download the xdebug version that matched your php version. Rename it to php_xdebug.dll. Add the php path to your environment variables (c:;\php). Then run valet install at a command prompt. It will install valet without error.

**Comment by vdhruv** [comment]
Thanks for the help @Nulimitz , it worked!

**Comment by jamesj2** [comment]
The pull request version worked for me.

`Set-ExecutionPolicy RemoteSigned -Scope Process; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri "https://raw.githubusercontent.com/cretueusebiu/valet-windows/85cda419c6fbe5815fb2e5bc3f2026b14d8a4479/bin/php.ps1" -OutFile $env:temp\php.ps1; .$env:temp\php.ps1 "8.1"`

**Comment by cretueusebiu** [comment]
Fixed #201
