### ISSUE TITLE
Packed not installed correctly

### ISSUE THREAD

**Issue by tonimitrevski** [cretueusebiu/valet-windows#21]
Please look this issue
![not_install](https://cloud.githubusercontent.com/assets/15773773/24791122/3789dc08-1b79-11e7-8224-175b4bf25b2d.jpg)

**Comment by cretueusebiu** [comment]
Do you have another version already installed ? If so make sure to stop it and uninstall it.

**Comment by tonimitrevski** [comment]
It's okay now, but ngnix can't to start. same problem

**Comment by cretueusebiu** [comment]
Can you check and post the logs ?

**Comment by tonimitrevski** [comment]
[Log.zip](https://github.com/cretueusebiu/valet-windows/files/908491/Log.zip)
That is it
