### ISSUE TITLE
Custom nginx conf

### ISSUE THREAD

**Issue by haziqfiqri** [cretueusebiu/valet-windows#211]
Is there a way that I can add certain stuff on the nginx? I needed to proxy my react app. But I can't find anything inside `/.config/valet` folder regarding nginx except `Nginx` folder that have a `.keep` file.

cc: @cretueusebiu

**Comment by cretueusebiu** [comment]
You have to secure your site first (`valet secure myapp`) then you can edit `~/.config/valet/Nginx/myapp.test.conf`. Don't forget to run `valet restart` after you change the config file.

**Comment by haziqfiqri** [comment]
Thanks @cretueusebiu for the clarification, perhaps add this on the README.
