### ISSUE TITLE
Error Install On Windows 11, PHP 8,1

### ISSUE THREAD

**Issue by alhazza73** [cretueusebiu/valet-windows#216]
![Screenshot 2023-08-23 193141](https://github.com/cretueusebiu/valet-windows/assets/142996523/1d4f0f1b-6ebb-46a0-8f62-30b11144b3a5)

**Comment by alhazza73** [comment]
i deleted composer folder ,,, i it's fixed

**Comment by rafiharli** [comment]
I have the same issues, can you tell me exactly what folder of composer to delete?

**Comment by CandraWijaya06** [comment]
could you tell which composer folder to delete?

**Comment by thalescarrascal** [comment]
> ![Screenshot 2023-08-23 193141](https://user-images.githubusercontent.com/142996523/262668956-1d4f0f1b-6ebb-46a0-8f62-30b11144b3a5.png)

could you tell which composer folder to delete?

**Comment by denysafrudin** [comment]
delete composer folder on your C:\Users\username\AppData\Roaming

**Comment by alhazza73** [comment]
thanks ,, it's work @denysafrudin
