### ISSUE TITLE
Fix WSL or WSL2 issue with AcrylicDNS

### ISSUE THREAD

**Issue by ryahconstantino** [cretueusebiu/valet-windows#219]
Change your AcrylicConfiguration.ini that is on: %appdata%/composer/vendor/cretueusebiu/valet-windows/bin/acrylic/AcrylicConfiguration.ini

LocalIPv4BindingAddress=0.0.0.0
to
LocalIPv4BindingAddress=127.0.0.1

Now you can run WSL2 + AcrylicDNS together :)

**Comment by ryahpalma** [comment]
@cretueusebiu Can you set this as default configuration for AcrylicDNS?
