### ISSUE TITLE
Valet share not working because space in Windows User folder name

### ISSUE THREAD

**Issue by Hendriksie** [cretueusebiu/valet-windows#25]
I can't get `valet share` working because the path is invalid.

The correct path is `C:\Users\Wesley Hendriks\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\cli\..\bin\ngrok` but I receive the following error: `The system cannot find the file C:\Users\Wesley`.

Probably because I have a space in my Windows User folder name.

I tried several escape methods but it does not seem to work.

**Comment by cretueusebiu** [comment]
Use the master branch until the next release:

```bash
valet stop
valet uninstall
composer global require cretueusebiu/valet-windows dev-master
valet install
```

**Comment by Hendriksie** [comment]
Thank you!
