### ISSUE TITLE
Problems with Active Directory Profiles (Set Config Path)

### ISSUE THREAD

**Issue by okaufmann** [cretueusebiu/valet-windows#26]
Hi,

I'm using Valet on several Windows Workstations. All works fine except the one joined in an Active Directory.

The Problem is the User Profile Path, there is a Local one (C:\Users\MyUsername) and the AD-Profile Path points to an Network Share (like U:\) where Valet should always use the local one.

Is there a Way to set the "Config-Dir" explicit for such situations?

```php
PHP Warning:  file_get_contents(U://.valet/config.json): failed to open stream: No such file or directory in C:\Users\MyUsername\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\cli\Valet\Filesystem.php on line 118

Warning: file_get_contents(U://.valet/config.json): failed to open stream: No such file or directory in C:\Users\MyUsername\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\cli\Valet\Filesystem.php on line 118
```

**Comment by cretueusebiu** [comment]
Valet uses [$_SERVER['HOME']](https://github.com/cretueusebiu/valet-windows/blob/master/cli/includes/helpers.php#L9) (or `$_SERVER['USERPROFILE']` as fallback) to determine the home path.

You can override it by adding an system environment variable named `HOME` with your new path.

**Comment by okaufmann** [comment]
Works, thanks!
