### ISSUE TITLE
valet install is not recognized. 

### ISSUE THREAD

**Issue by Hujjat** [cretueusebiu/valet-windows#27]
I have composer and PHP installed in my PC. I am running windows 10 and followed the instructions. When I run the `valet install` I get this error` 'valet' is not recognized as an internal or external command,` 

I know it's not added to environment path, But the doc didn't say anything about that. How can solve this problem? 

Thanks :)

**Comment by cretueusebiu** [comment]
If you install Composer with the installer it will  automatically add the bin path to your env variable. Otherwise you'll have to add it manually.
