### ISSUE TITLE
Question: Valet (php 7.1) and XAMPP (5.6) alongside

### ISSUE THREAD

**Issue by dandruff123** [cretueusebiu/valet-windows#28]
Hello, I really appreciate your effort to bring **Valet** for Windows machines. I want to clarify something not only for myself, but for everyone who is new in multiple server solutions on one machine.Let's say that I need to have **XAMPP** installed on my Windows machine for other projects that require `PHP 5.6`.

- Does that mean that I won't be able to activate Apache, or maybe I can try changing `port 80` to other one on either Apache or Valet? Can I have them both running?
- If not, can I have only Valet running for my XAMPP configured projects on PHP 5.6 ? Even if that would mean moving project folders elsewhere.

I would like to hear your opinion on this topic and any possible solutions, or maybe I should keep using XAMPP for now (with respect for your work)

Regards

**Comment by cretueusebiu** [comment]
Changing the port on Valet is not possible right now (at least it's not yet implemented on the official version).

But if you still want to run XAMPP just stop valet with `valet stop` then start XAMPP. 

The only thing where you might run into problems is with the env path to PHP. XAMPP will set its PHP (5.6) path by default and Composer will most likely pick that when it's first installed.

But then if you want PHP 7.1 for Valet you also have to add it to your env path (when you install PHP 7.1 with the included installer it will add the path to your env automatically) and then you might have to also reinstall Composer to pick the new PHP path.

So the only problematic thing is that you have two versions of PHP. 
You could try to write a bash/batch script that switches those paths for you.
