### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by Francismori7** [cretueusebiu/valet-windows#29]
Chrome 58+ issue here.

See https://github.com/laravel/valet/issues/369

Same thing, cannot secure the sites, certificate is not "safe" as of Chrome 58

**Comment by cretueusebiu** [comment]
I'm using [phpseclib](https://github.com/phpseclib/phpseclib) to create the certificate, but I can't find how to set `subjectAltName`.

**Comment by Francismori7** [comment]
@cretueusebiu http://phpseclib.sourceforge.net/x509/guide.html

**Comment by Francismori7** [comment]
I actually fixed it, see my PR.
