### ISSUE TITLE
Not able to install after unistall

### ISSUE THREAD

**Issue by skakrecha** [cretueusebiu/valet-windows#34]
I am not able to install valet again as composer is showing "folder already exists", i also tried removing valet from composer.json file , not able to delete the folder manually as nginx and other services are running, tried manually stopping them with no luck deleting the old valet folder in composer.Please help

**Comment by cretueusebiu** [comment]
Make sure to stop everything before you uninstall it. Run `valet stop` then `valet uninstall`.
