### ISSUE TITLE
Could I change port 80 to other port(8080)

### ISSUE THREAD

**Issue by zohaibhassan156** [cretueusebiu/valet-windows#38]
Could I change port for valet to other than 80?

**Comment by cretueusebiu** [comment]
Unfortunately it can't be changed.

**Comment by zohaibhassan156** [comment]
Ok, thanks for your help

**Comment by tsdeveloper** [comment]
Olá se você deseja alterar a porta do Valet, precisar acessar esse arquivo **valet.conf**
Local: **C:\Users\Seu-Usuário\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx\valet**

Inglish

Hello, if you want to change the Valet port, you need to access this file ** valet.conf **
Location: ** C: \ Users \ Your-User \ AppData \ Roaming \ Composer \ vendor \ cretueusebiu \ valet-windows \ bin \ nginx \ valet **
![valet port](https://user-images.githubusercontent.com/5727326/51131782-cdf1c880-1817-11e9-9732-cbf4b16af5dd.png)
![valet](https://user-images.githubusercontent.com/5727326/51131783-ce8a5f00-1817-11e9-9859-3e9208896de9.png)
