### ISSUE TITLE
'valet' is not recognized...

### ISSUE THREAD

**Issue by getanwar** [cretueusebiu/valet-windows#39]
`'valet' is not recognized as an internal or external command, operable program or batch file.`

I have successfully downloaded valet using composer after running `composer global require cretueusebiu/valet-windows` command. But when I tried to follow 3rd command which is "Run the `valet install` command" it didn't work for me. I got the issue mentioned above every time, even after I relaunched the terminal. 

NB: Composer path is set to my machine's Environment Variable manually.

**Comment by cretueusebiu** [comment]
This usually happens when the path to composer's bin directory is not set up properly. Reinstall composer and make sure to check the box that adds the path.
