### ISSUE TITLE
Host File Not Updated

### ISSUE THREAD

**Issue by victormongi** [cretueusebiu/valet-windows#41]
valet-windows helping my dev life...
But I have a problem valet-windows not updating the host file... I have to update manually.
I know that I don't have to edit my host file, I just need have to connect to the at least to a network to make this work, but sometimes
I don't have any connection so I have to edit the host file...
I really need help...
Thank you....

**Comment by cretueusebiu** [comment]
Hi, Valet does not edit your hosts file, instead it uses Acrylic DNS and proxies all requests on the *.dev .
So if you don't have at least a network Acrylic won't work so you'll have to manually add the domains to your hosts file.

**Comment by victormongi** [comment]
Could I request this feature, for autoupdating the host file,
Anyway this package is awesome... and fast response from the creator...
Thank you @cretueusebiu...

**Comment by cretueusebiu** [comment]
That's the point of Valet, to not change your hosts file...
