### ISSUE TITLE
Stopping Valet stops internet connection from working

### ISSUE THREAD

**Issue by adevade** [cretueusebiu/valet-windows#47]
Whenever I run `valet stop` in cmd or PowerShell my internet connection stops working completely, until I run `valet start` again. 

What could be causing this, and is there a way to fix it?
I'm guessing this is something I have configured wrong on my system, but I can't seem to find what. 

Thanks for a great application!

**Comment by adevade** [comment]
I just got it working by adding Googles Public DNS (8.8.8.8) as an "Alternative DNS" in my network settings! Right below 127.0.0.1.

**Comment by cretueusebiu** [comment]
That should be configured automatically when you install Valet by [this script](https://github.com/cretueusebiu/valet-windows/blob/master/bin/configuredns.bat). 
If that doesn't work you'll have to configure the DNS Proxy [manually](http://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration).
