### ISSUE TITLE
cant get valet to serve a site

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [cretueusebiu/valet-windows#48]
I installed valet-windows via PowerShell runnin as admin. I got these warnings, but it seemed to install
```
PHP Warning:  copy(C:/Users/array/.valet/Services/nginxservice.exe): failed to open stream: Resource temporarily unavail
able in C:\Users\array\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\cli\Valet\Filesystem.php on line 193
PHP Warning:  copy(C:/Users/array/.valet/Services/phpfpmservice.exe): failed to open stream: Resource temporarily unavai
lable in C:\Users\array\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\cli\Valet\Filesystem.php on line 193
```
I then did the usual `valet park`, and when i browsed to my site `jpe.dev`, I got a `ERR_ICANN_NAME_COLLISION` error in the browser

So I tried adding `127.0.0.1	jpe.dev` to my hosts file, and now im seeing this:
```
Not Found
HTTP Error 404. The requested resource is not found.
```

I installed valet-windows via composer, but I already had my own copy of php 7.1 installed, when I type `php -v` in PowerShell I see
```
PHP 7.1.8 (cli) (built: Aug  1 2017 21:10:46) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by cretueusebiu** [comment]
Make sure to uninstall the Valet services. Then install it again.
