### ISSUE TITLE
Stops other composer global tasks running in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by Ascerta** [cretueusebiu/valet-windows#49]
When running a globally installed composer application, e.g Envoy in the Windows Subsystem for Linux/bash for windows environment the valet compatibility check:

```
if (PHP_OS !== 'WINNT' && !$inTestingEnvironment) {
    echo 'Valet for Windows only supports the Windows operating system.'.PHP_EOL;
  exit(1);
}
```
Causes the execution to halt even if valet wasn't called. E.e if  "Envoy" was being called this check is still run and execution will exit.

Could the compatibility check be moved to only be called if a valet function is called or make the check result in a warning rather than exit.

**Comment by cretueusebiu** [comment]
Fixed in 2.0.12.
