### ISSUE TITLE
504 ERROR

### ISSUE THREAD

**Issue by joelpiccoli** [cretueusebiu/valet-windows#53]
I keep getting the 504 Gateway Time-out error on my installation of valet-windows. I checked the port, I manually configured the acrylic dns and parked the valet on the right folder. Anyone know any possible reason for this happen?

**Comment by cretueusebiu** [comment]
Check the log files in `~/.valet/Log`.

**Comment by joelpiccoli** [comment]
the log is:
2017/10/25 11:24:34 [error] 7220#5092: *22 upstream timed out (10060: FormatMessage() error:(15105)) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mywebsite.localhost", referrer: "http://mywebsite.localhost/"

**Comment by cretueusebiu** [comment]
Just to be sure, install version 2.0.11.

```
valet stop
valet uninstall

composer global update cretueusebiu/valet-windows:2.0.11

valet install
```

**Comment by joelpiccoli** [comment]
Well, It works! I complete uninstall everything and installed again and now everything works like a clock... thanks!

**Comment by cretueusebiu** [comment]
Just to be sure, did you installed 2.0.11 or the latest, 2.0.12 ?

**Comment by clarknelson** [comment]
Something worth noting here (maybe) is the server parameter is blank in the error message. Do you think this is related to the error?
