### ISSUE TITLE
Valet no longer working after a windows update 

### ISSUE THREAD

**Issue by jesseyofferenvan** [cretueusebiu/valet-windows#54]
My valet on windows has stopped working after an windows update

`Jessey@DESKTOP-ATMMBDH MINGW64 /c`
`$ valet start`
`Could not start the phpfpmservice service. Check ~/.valet/Log for errors.`

When I cat the phpfpmservice wrapper I get the following

2017-11-01 14:38:47,443 INFO  - Starting ServiceWrapper in the CLI mode
2017-11-01 14:38:47,578 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   at winsw.WrapperService.ThrowNoSuchService()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

Now I wonder if theres something obvious I can try to do?

**Comment by cretueusebiu** [comment]
Try:

```
valet stop
valet uninstall
valet install
```

**Comment by jesseyofferenvan** [comment]
@cretueusebiu  this is the response once I try it

**Comment by cretueusebiu** [comment]
Did you run the CMD as admin mode ?

**Comment by jesseyofferenvan** [comment]
I just tried with launching CMD as administrator, during uninstalling and installing there where no errors, but trying to park into my drive and trying to launch the sites does not seem to work even when I edit my network adapter settings

**Comment by cretueusebiu** [comment]
Run `valet stop`, delete the log files, then run `valet start`. 
Then access your sites again and check the logs for errors.

**Comment by jesseyofferenvan** [comment]
It seems that valet_phpfpm is stuck, but I can't find it anywhere in my process list or resource list of my computer. 

$ rm -f phpfpmservice.*
rm: cannot remove 'phpfpmservice.err.log': Device or resource busy
rm: cannot remove 'phpfpmservice.out.log': Device or resource busy

**Comment by harblz** [comment]
I had a similar issue, receiving the same original error messages. Following the steps above resolved the issue for me.

One note: Acryllic DNS appears (with the new fall creator's update) appears to not resolve DNS properly on startup and no internet services work. 

I'm unsure if this is unique to me or related to valet - the workaround is to allow it to change the ethernet adapter's IP4 / IP6 properties resolve the DNS automatically, then go back and set them to 127.0.0.1 and ::1 respectively. After that, valet works fine.

**Comment by zymawy** [comment]
Lest Post The @cretueusebiu  Declare Worked For My 
1 - I Stop The Server By This Commend `valet stop` ,
2 - I Delete All The Files Log In The `username/.valet/Log` Folder ,
3 - Than I run This Commend `valet start` ,
4 - I Setup The DNS Config Linked [Here ](http://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration), 

Done

**Comment by fozoholiver1** [comment]
I ran cmd as admin and did
valet uninstall
valet install
