### ISSUE TITLE
Using the required Acrylic DNS entries prevents some websites from working

### ISSUE THREAD

**Issue by janschloss** [cretueusebiu/valet-windows#55]
Hey,

after using the DNS settings described in the linked Acrylic DNS guide some websites do either not work – or some assets are not loaded correctly (css/images/...).

Is there anything to fix this issue?

Or is there any way to not use Acrylic DNS for Valet on Windows?

**Comment by cretueusebiu** [comment]
I know. I had the same issue with Steam, and took me forever to realize that it was from Acrylic. Somehow it works now, but I'm not sure what's the cause.
