### ISSUE TITLE
"valet secure" creates a cert that won't be valid until one hour later

### ISSUE THREAD

**Issue by joewhite** [cretueusebiu/valet-windows#57]
I ran "valet secure test1" and then tried to browse out to https://test1.dev, and got Chrome's "Privacy error" page. When I clicked "Advanced", it said "This server could not prove that it is test1.dev; its security certificate is supposedly from 0 days in the future. This may be caused by a misconfiguration or an attacker intercepting your connection."

When I went into Chrome's browser tools > Security tab > View certificate > Details page, it showed that the certificate's "Valid from" date/time was one hour into the future. I had run "valet secure test1" at 12:04 AM; the certificate's "Valid from" date was today at 1:04 AM.

I'm in US Central standard time (UTC-06:00) if it makes a difference.

**Comment by cretueusebiu** [comment]
Can you create a new certificate (with the latest version of Valet) and post it here ? 
The certificates are stored in `~/.valet/Certificates`.
