### ISSUE TITLE
Initial Install

### ISSUE THREAD

**Issue by evansvince** [cretueusebiu/valet-windows#59]
Do I need to install Acrylic DNS manually?

I've used Valet on Mac for over a year now but cant launch the site/domain on Windows. Any help is greatly appreciated.

**Comment by cretueusebiu** [comment]
No. But few have reported that they need to [configure it manually](http://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration). 

If that still doesn't work check the logs in `~/.valet/Logs`.

**Comment by evansvince** [comment]
Got it. I needed to configure it. Thanks!
