### ISSUE TITLE
PHP-FPM exits after 500? requests, making Valet unusable (502 Bad Gateway)

### ISSUE THREAD

**Issue by huncrys** [cretueusebiu/valet-windows#6]
After some googling and reading through the PHP-FPM documentation, I've added `PHP_FCGI_MAX_REQUESTS=0` to the global environment variables, issued a `valet restart` and haven't experienced this issue since then.

Maybe you could set this before starting the PHP-FPM process, or refer this solution in the README.

**Comment by cretueusebiu** [comment]
Hi, where exactly did you set this ? In the Windows environment variables  ?

**Comment by huncrys** [comment]
Yes, in `Control Panel / System / Advanced system settings / Environment variables...`

**Comment by cretueusebiu** [comment]
I had some issues with PHP-FPM prior to 2.0.5 because the service would sometime crash. But since 2.0.5 if the service crashes it will restart automatically. 

What version of Valet do you have ?

**Comment by huncrys** [comment]
Ah, you are right... I missed the upgrade, I was still on 2.0.4. Closing this.
