### ISSUE TITLE
refused to connect.

### ISSUE THREAD

**Issue by atef201080** [cretueusebiu/valet-windows#60]
i just installed valet in Windows 10 Pro Version 1709 Build 16299.125
Installed Composer and php using Choco app and they both working
but when i try to open a project in browser it says blog.app refused to connect.
tried with test domain didn't work tried changing the domain to app also didn't work the same error
i used valet park on the projects directory
also when opening localhost in browser it says Valet - Not Found
even the same error when linking a directory using valet link.

**Comment by cretueusebiu** [comment]
Have you checked `~/.valet/Logs` ?

**Comment by atef201080** [comment]
after few restarts and reinstall few times it's working now at test domain and stops when changing the domain even when i try restarting..

**Comment by cretueusebiu** [comment]
Make sure the domain is `.test`
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/
