### ISSUE TITLE
Timeout after update to 2.0.13

### ISSUE THREAD

**Issue by okaufmann** [cretueusebiu/valet-windows#61]
Hi, I'm using valet since a year ago. I was always happy with it and had no problems.

But after the update to 2.0.13 and stop, uninstall and install again I can't reach any of my local dev sites.
The request runs endless untill the nginx proxy timeout is exceeded...

What I tried:
- Reinstall php (new config, new download, newest 7.1 version, TS and NTS builds)
- Remove valet-windows from composer and reinstall
- remove ~\.valet folder and reinstall
- All these steps with and without admin permissions
- Tried this on two separate pcs

I always get this: 
![image](https://user-images.githubusercontent.com/4414498/34004889-7e5cd4b4-e0f9-11e7-962a-d641fbb067c5.png)

What I also noticed:
- I can't stop the php-cli.exe via valet stop I have to kill it via task manager
- I can't run any cli while a request is waiting

BUT:
When I configure the port back to 9000 in the following files it's working again.
- ~\.valet\Service\phpfpmservice.xml
- ~\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx\valet\valet.conf

I have no plan why this behaves like that... Any suggestions / tips ?

**Comment by cretueusebiu** [comment]
Is maybe port 9001 used by something else on your machine ? Have you checked the Logs folder ?

**Comment by okaufmann** [comment]
I double checked there is no other process using port 9001.  I restarted my pc and did a `netstat -a -b` to find out there is no other proccess using this port... 

does no one else have these problems? (by the way, why did you change the port to 9001? just to know)

**Comment by cretueusebiu** [comment]
No one reported this issue so far.
https://github.com/cretueusebiu/valet-windows/pull/51

**Comment by okaufmann** [comment]
Suggest let it open for a while and then close it if nobody else have trouble...

**Comment by cretueusebiu** [comment]
If more people have this problem we could add a `--port` option when you install it.

**Comment by chandrastrez** [comment]
Me too,,

![image](https://user-images.githubusercontent.com/34904120/34400069-3d377f4e-ebc0-11e7-8062-29f2f2539a29.png)

`[error] 9500#11604: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "hasta.test"`

Configure the port back to 9000 not work for me

Thanks

**Comment by cretueusebiu** [comment]
Can someone with this problem contact me privately so I can take a look via Team Viewer ? 
(You can find my email on the GitHub profile)

**Comment by okaufmann** [comment]
Did you find the reason causing this problem? I installed vallet last week on a fresh install of windows 10 pro and had the same problem.... After changing the Port to 9000 it worked. I'll contact you via mail for further diagnostics.

**Comment by cretueusebiu** [comment]
@okaufmann I helped few others via TW, but it wasn't from the port, just other misconfigured things. Yes contact me. If is from the port then I could add a custom install option that changes the port.

**Comment by JohnTheo13** [comment]
@cretueusebiu I'm having the same error here, if it's not the port which config do i need to change?

**Comment by robmarshall** [comment]
This has been an ongoing issue for me as well

**Comment by Francismori7** [comment]
Same here.
