### ISSUE TITLE
Acrylic DNS proxy -> no internet

### ISSUE THREAD

**Issue by Gino** [cretueusebiu/valet-windows#62]
Hello,

When I install Valet and follow the 'Acrylic DNS proxy' installation, my internet doesn't work anymore.
Could you help me with this?

Thanks.

**Comment by cretueusebiu** [comment]
It happened to me once or twice but it solved itself. Something to do with Acrylic DNS, not sure what can be done.

**Comment by Gino** [comment]
Well, my Valet websites are working now. But Windows says that the DNS server isn't responding, so I have no internet at all.

**Comment by Gino** [comment]
Well, my Valet websites are working now. But Windows says that the DNS server isn't responding, so I have no internet at all.

**Comment by atef201080** [comment]
in dns 1 put 127.0.0.1 in dns 2 use 8.8.8.8.. tbh i works with me without using Acrylic DNS

**Comment by cretueusebiu** [comment]
Are you sure ? Check your services and Acrylic DNS should be the.

**Comment by SYNTAG** [comment]
I am having the same issue. It worked fine for a couple hours with the Acrlyic DNS. However, I lost my internet as well. I did what @atef201080 suggested and added 8.8.8.8 as my alternative DNS and it brought my internet back.

However, I was having issues with valet after that. I was getting this strange: "MIB search path: /usr/share/snmp/mibs" error every time I ran a command with valet:
```Cannot find module (IP-MIB): At line 0 in (none)
Cannot find module (IF-MIB): At line 0 in (none)
Cannot find module (TCP-MIB): At line 0 in (none)
Cannot find module (UDP-MIB): At line 0 in (none)
Cannot find module (HOST-RESOURCES-MIB): At line 0 in (none)
Cannot find module (SNMPv2-MIB): At line 0 in (none)
Cannot find module (SNMPv2-SMI): At line 0 in (none)
Cannot find module (NOTIFICATION-LOG-MIB): At line 0 in (none)
Cannot find module (UCD-SNMP-MIB): At line 0 in (none)
Cannot find module (UCD-DEMO-MIB): At line 0 in (none)
Cannot find module (SNMP-TARGET-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-AGENT-MIB): At line 0 in (none)
Cannot find module (DISMAN-EVENT-MIB): At line 0 in (none)
Cannot find module (SNMP-VIEW-BASED-ACM-MIB): At line 0 in (none)
Cannot find module (SNMP-COMMUNITY-MIB): At line 0 in (none)
Cannot find module (SNMP-FRAMEWORK-MIB): At line 0 in (none)
Cannot find module (SNMP-MPD-MIB): At line 0 in (none)
Cannot find module (SNMP-USER-BASED-SM-MIB): At line 0 in (none)
Cannot find module (SNMP-NOTIFICATION-MIB): At line 0 in (none)
Cannot find module (SNMPv2-TM): At line 0 in (none)```

More importantly, my valet links were not hitting my API anymore. After noticing this, I removed the secondary DNS from earlier and reloaded Valet. Now my Valet projects and Internet works.

I suspect that my internet will probably go down again. Any idea why the Acrylic DNS expires connection to internet overtime? Appreciate it!
