### ISSUE TITLE
http doesn't seem to work on parked projects...

### ISSUE THREAD

**Issue by karlkras** [cretueusebiu/valet-windows#65]
Hello, thanks for this product. I'd really like to get it working.
I've installed on a windows 10 box as administrator. Seems to be functionally working fine, e.g., stop, start, restart working as expected. However, I cd in to my laravel project root location and do:

`$> valet park  `

it comes back with this:

```
This directory has been added to Valet's paths.
```
which is still cool.

Now if I ping one of my projects...

```
$ ping customapp.dev

Pinging customapp.dev [127.0.53.53] with 32 bytes of data:
Reply from 127.0.53.53: bytes=32 time<1ms TTL=128
```
(and of course trying to hit http://customapp.dev fails.)
and I've performed the Network dns configuration as mentioned with using AcrylicHosts. but still have this default redirect. Not sure where to go with this. Google isn't providing much more then what 

Could you please provide a hint on what else I should be looking at?

**Comment by cretueusebiu** [comment]
You can't use .dev or .app any more. Use `valet domain test` to change it to .test

**Comment by karlkras** [comment]
Okay..., changed that, restarted valet and now:
```
$ ping customapp.test

Pinging customapp.test [::1] with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
```

but when I hit http://customapp.test I'm getting a 404
