### ISSUE TITLE
Resource temporarily unavailable when reinstalling

### ISSUE THREAD

**Issue by abrhambas01** [cretueusebiu/valet-windows#66]
I uninstalled valet and installed it once again but this time it shows something like this : 

$ valet install
Stopping nginx...
Installing nginx configuration...
Installing nginx directory...
PHP Warning:  copy(C:/Users/Samsung/.valet/Services/nginxservice.exe): failed to open stream: Resource temporarily unavailable in C:\Users\Samsung\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\cli\Valet\Filesystem.php on line 193

Warning: copy(C:/Users/Samsung/.valet/Services/nginxservice.exe): failed to open stream: Resource temporarily unavailable in C:\Users\Samsung\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\cli\Valet\Filesystem.php on line 193
Could not install the nginxservice service. Check ~/.valet/Log for errors.

**Comment by cretueusebiu** [comment]
You probably forgot to stop Valet.
Run `valet stop` and then `valet uninstall `

**Comment by abrhambas01** [comment]
@cretueusebiu I would like to start from the first step. I followed all your instructions but Still I get so many errors.  Is there something I lacked doing ?

**Comment by abrhambas01** [comment]
This site can’t be reached
This site on the company, organization or school intranet has the same URL as an external website. 

Try contacting your system administrator.
ERR_ICANN_NAME_COLLISION

I get that.

**Comment by cretueusebiu** [comment]
After you run `valet stop` and `valet uninstall` can you check if these 3 services are still running ? 

![screenshot_1](https://user-images.githubusercontent.com/1517945/34608904-3bcedad0-f223-11e7-8572-b6ae5a0f99b0.png)
![screenshot_2](https://user-images.githubusercontent.com/1517945/34608905-3dd937ee-f223-11e7-9651-49b12747ceb1.png)

**Comment by abrhambas01** [comment]
I have some questions @cretueusebiu since We have different timezone

1. I have installed already xampp in my computer. What i did is to skip this first step ?

`Set-ExecutionPolicy RemoteSigned; Invoke-WebRequest -Uri "https://github.com/cretueusebiu/valet-windows/raw/master/bin/php71.ps1" -OutFile $env:temp\php71.ps1; ."$env:temp\php71.ps1"`



> Since xampp has already php in it.


2. I use cmder as my terminal in doing the later steps. Is it ok ? 

3. Do i have to modify to the hosts file because I've seen an comment in laracasts regarding your package that I have to modify the hosts file ?

**Comment by abrhambas01** [comment]
@cretueusebiu  they're not running

**Comment by abrhambas01** [comment]
ping foo.dev

Pinging foo.dev [127.0.53.53] with 32 bytes of data:
Reply from 127.0.53.53: bytes=32 time<1ms TTL=128
Reply from 127.0.53.53: bytes=32 time<1ms TTL=128
Reply from 127.0.53.53: bytes=32 time<1ms TTL=128
Reply from 127.0.53.53: bytes=32 time<1ms TTL=128

**Comment by abrhambas01** [comment]
@cretueusebiu  I really don't like the localhost: bla bla bla, I'd love to use your product, and in what way I can help, I would. Can you please help me ?

**Comment by cretueusebiu** [comment]
If you already have PHP you can skip that step. 
You can use any terminal you prefer.
You don't need to modify the hosts, Valet will manage everything.

Don't use `.dev` use `.test`. Use `valet domain test` to change the tld to `.test` because Chrome will redirect `http://site.dev` to  `https://site.dev` and if you didn't secure it won't work. https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by abrhambas01** [comment]
Thank you @cretueusebiu It worked now. Thanks a lot
