### ISSUE TITLE
Website Doesn't work without active internet connection.

### ISSUE THREAD

**Issue by sagarrabadiya** [cretueusebiu/valet-windows#67]
If I am not connected to internet, then none of the local site *.test is working, instead browser shows you are not connected internet (offline) page. Is there any way i can still keep nginx running if there is no internet connection, when there is no internet connection other nginx confs (sites) are also not working. everything gets stopped if I am not connected to internet connection.
  
also installing latest version gives error about symfony/process component. check below

![image](https://user-images.githubusercontent.com/5405403/34765671-23bc9ae2-f618-11e7-9e9b-90252634b160.png)

**Comment by cretueusebiu** [comment]
I just published [2.0.15](https://github.com/cretueusebiu/valet-windows/releases/tag/2.0.15) that adds compatibility with symfony/process v4.

**Comment by sagarrabadiya** [comment]
is there any possibility to make it work offline as well, i mean without active internet connection?

**Comment by ponchacc** [comment]
> is there any possibility to make it work offline as well, i mean without active internet connection?

A connection to the internet is required. Otherwise you'll have to add your domain manually in your hosts file. 
(This worked for me in 06 Feb, 2022 )
