### ISSUE TITLE
Phalcon support.

### ISSUE THREAD

**Issue by atef201080** [cretueusebiu/valet-windows#68]
i like to use valet for all my project instead of installing xampp which has features i don't really need..
I've tried to use Phalcon framework but i got this error.

Mod-Rewrite is not enabled
Please enable rewrite module on your web server to continue

**Comment by cretueusebiu** [comment]
You need to add a custom driver in `~/.valet/Drivers`.  See [Custom Valet Drivers](https://laravel.com/docs/5.5/valet#custom-valet-drivers).

There are some already created: https://google.com/search?q=Phalcon+Valet
