### ISSUE TITLE
nginx: [emerg] bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)

### ISSUE THREAD

**Issue by Ravin001** [cretueusebiu/valet-windows#69]
I know this is an issue because port 80 is being used. I  am unable able to find the config file for ngnix where I can change the port for Nginx server. Can anybody help me with this query?

**Comment by cretueusebiu** [comment]
This was asked on the official Valet repo, but it seems that it won't work without a lot of changes.
