### ISSUE TITLE
Line 17: /valet: No such file or directory

### ISSUE THREAD

**Issue by tushiee** [cretueusebiu/valet-windows#7]
Hello,

I am pretty sure that this issue doesn't occur cause your Valet project but this error also occurs when I try to use the `laravel new` command. But I have actually no freaking idea how this is coming, and it this error comes back when I try to use the `valet install` command.

The error:
![](http://i.imgur.com/2Esyqqb.png)

As you can see it says:
**Line 17: /valet: No such file or directory**

If I browse to that actual file, this is the content:
http://pastebin.com/raw/bXDPCEJe

Could you maybe help me with this? Thank you.

**Comment by cretueusebiu** [comment]
Have you installed Valet via composer ?

**Comment by tushiee** [comment]
Yes I did, I also got this error/issue when I try to do the "laravel new" command

**Comment by cretueusebiu** [comment]
Reinstall composer and start again. Make sure the composer bin is added to your env path.

**Comment by tushiee** [comment]
I reinstalled Composer like 4 times already but it keeps giving me this error.
I also tried to add it to my path, but I am not 100% sure if it is right:
![](http://i.imgur.com/4iCl8OD.png)

**Comment by cretueusebiu** [comment]
Try a computer restart maybe. But do any other composer CLI  tools give you this error ?

**Comment by cretueusebiu** [comment]
After you require valet, does it appear in the bin directory?

**Comment by tushiee** [comment]
Sorry for my late response but I tried some stuff and now it kinda works, atleast I can run the command:
`composer global require cretueusebiu/valet-windows`, but when I try to run `valet install`, it says: 
"bash: valet: command not found"

**Comment by cretueusebiu** [comment]
It looks like the composer/bin folder is not added to your env path.

**Comment by tushiee** [comment]
I have added the composer/bin in my path, but now it says:
`Could not open input file: /cygdrive/c/Users/Gino/AppData/Roaming/Composer/vendor/cretueusebiu/valet-windows/valet`

**Comment by cretueusebiu** [comment]
Are you using Cygwin ?

**Comment by tushiee** [comment]
Yes I am, via ConEmu. I tried many commands with the normal Windows cmd but there are all the commands, like `laravel` or `valet` not recognized

**Comment by cretueusebiu** [comment]
I guess it's all because of Cygwin. I'll try it myself and see what's wrong.

**Comment by tushiee** [comment]
But why are all my commands not working in normal Windows cmd then? :(
I cannot use normal Windows cmd then, because all the commands aren't working. They are all not recognized

**Comment by cretueusebiu** [comment]
Maybe because of Cygwin is still installed.. I use https://git-scm.com

**Comment by tushiee** [comment]
What is the best way to start all over again? Should I remove Composer, Cygwin, Git Bash etc.?

**Comment by cretueusebiu** [comment]
Yes, remove everything, install composer via the [installer](https://getcomposer.org/download/) then Git Bash.

**Comment by tushiee** [comment]
And how should I reset my path etc.? Because I tried before with Git Bash but then I add this `Line: 17 /laravel` problem, why I actually started this issue.

**Comment by cretueusebiu** [comment]
Edit the `Path` env variable and remove what you don't need from there. When you install composer again it should add it's path there back.

**Comment by tushiee** [comment]
Okay, and is that https://git-scm.com/ also a cmd thing? Or should I use Git Bash ?

**Comment by cretueusebiu** [comment]
Try first just with CMD.

**Comment by tushiee** [comment]
Okay, currently everything is working fine with normal cmd but when I try to run `valet install`, it returns:
`Could not install the nginxservice service. Check ~/.valet/Log for errors.`

And when I look in the nginxservice.wrapper file, it says:
`2017-01-25 14:13:34,854 INFO  - Starting ServiceWrapper in the CLI mode
2017-01-25 14:13:35,010 FATAL - WMI Operation failure: AccessDenied
WMI.WmiException: AccessDenied
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
`

**Comment by cretueusebiu** [comment]
You must run CMD as administrator.

**Comment by tushiee** [comment]
That worked, but when I go to my projects directory and when I run the `valet park` command, it all works. But when I go to laravel.dev, a 504 Gateway Time-out error comes on the page:
![](http://i.imgur.com/Z7auzbH.png)

And yes, the folder has the name Laravel and it takes very long to load the page and then the 504 error comes.

**Comment by cretueusebiu** [comment]
Check ~/.valet/Log/nginx-error.log

**Comment by tushiee** [comment]
nginx-error.log:
`2017/01/25 14:21:07 [error] 15144#10444: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "billing.dev"
2017/01/25 14:21:21 [error] 15144#10444: *4 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "examendb.dev"
2017/01/25 14:21:24 [error] 15144#10444: *7 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "laravel.dev"
2017/01/25 14:21:27 [error] 15144#10444: *10 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "plaatex.dev"
`

**Comment by cretueusebiu** [comment]
Can you check if these 3 services are running ![](http://image.prntscr.com/image/f22eb368d4e24d129d9e7f5d1d523b9d.png)

**Comment by tushiee** [comment]
They are all running except the valet_phpfpm, and when I try to run it, it instantly stops.

**Comment by cretueusebiu** [comment]
That service runs on port 9000. So I guess you already have something running on that port. Use [Resource Monitor](http://stackoverflow.com/a/23718720) and see what's running on that port.

**Comment by tushiee** [comment]
There is nothing running on port 9000, but in the wrapper.log it says 3 different php folders, because I have PHP 5.x (by xampp) and I have also PHP 7.x (that I downloaded myself and put in C:/php).
But there is nothing running on port 9000 and when I try to start the valet_phpfpm service, it isn't starting, it just instantly stop.

![](http://i.imgur.com/69MG7SP.png)

**Comment by cretueusebiu** [comment]
If you run `php -v` what it says ?

**Comment by tushiee** [comment]
`$ php -v
PHP 5.6.12 (cli) (built: Aug  6 2015 12:06:20)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies`

**Comment by cretueusebiu** [comment]
I've only tested valet it with PHP 7/7.1 so I guess it might be because you're using PHP 5. Edit your env path and make sure you only have the path to 7 there.

**Comment by tushiee** [comment]
I just updated to PHP 7.1 but it  still stops instantly, the log is:
`2017-01-25 14:18:48,294 INFO  - Starting ServiceWrapper in the CLI mode
2017-01-25 14:18:48,444 INFO  - Completed. Exit code is 0
2017-01-25 14:18:48,793 INFO  - Starting ServiceWrapper in the CLI mode
2017-01-25 14:18:48,976 FATAL - WMI Operation failure: ServiceCannotAcceptControl
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2017-01-25 14:18:49,414 INFO  - Starting ServiceWrapper in the CLI mode
2017-01-25 14:18:49,668 INFO  - Starting ServiceWrapper in the service mode
2017-01-25 14:18:49,725 INFO  - Completed. Exit code is 0
2017-01-25 14:18:51,941 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:18:51,944 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:18:52,190 INFO  - Completed. Exit code is 0
2017-01-25 14:28:21,070 INFO  - Starting ServiceWrapper in the service mode
2017-01-25 14:28:21,082 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:28:21,085 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:28:21,089 INFO  - Completed. Exit code is 0
2017-01-25 14:45:49,338 INFO  - Starting ServiceWrapper in the service mode
2017-01-25 14:45:49,353 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:45:49,355 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:45:49,360 INFO  - Completed. Exit code is 0
2017-01-25 14:45:50,726 INFO  - Starting ServiceWrapper in the service mode
2017-01-25 14:45:50,738 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:45:50,741 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:45:50,746 INFO  - Completed. Exit code is 0
2017-01-25 14:45:51,707 INFO  - Starting ServiceWrapper in the service mode
2017-01-25 14:45:51,720 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:45:51,722 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:45:51,727 INFO  - Completed. Exit code is 0
2017-01-25 14:47:20,413 INFO  - Starting ServiceWrapper in the service mode
2017-01-25 14:47:20,426 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:47:20,428 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:47:20,433 INFO  - Completed. Exit code is 0
2017-01-25 14:47:30,131 INFO  - Starting ServiceWrapper in the service mode
2017-01-25 14:47:30,143 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:47:30,146 INFO  - Starting C:\xampp\php\php.exe
C:\php\php.exe
C:\cygwin64\bin\php-cgi.exe -b 127.0.0.1:9000
2017-01-25 14:47:30,151 INFO  - Completed. Exit code is 0
` But I just deleted the C:\php folder and also the `C:\cygwin64\bin\php-cgi.exe` file and also the `C:\cygwin64\bin\php.exe` file.. but still the same problem.

**Comment by cretueusebiu** [comment]
It still detects xampp. It may still be in your env path. Make sure you only have a single PHP installed.

**Comment by cretueusebiu** [comment]
You'll have to reinstall valet again after you change your php.

**Comment by tushiee** [comment]
Okay, I am just removing whole XAMPP now and I just installed PHP 7.1 again in C:\php, but how do I actually reinstall Valet?? :/

**Comment by cretueusebiu** [comment]
```bash
valet stop
valet uninstall
valet install
```

**Comment by tushiee** [comment]
When I try to run those commands, it says:
`'php' is not recognized as an internal or external command,
operable program or batch file.`

But PHP is in C:\php\(php.exe) and I also added C:\php\ to my path but it still says that error, I also restarted cmd etc. but now its not working :/

**Comment by cretueusebiu** [comment]
Can you run `php -v`. Make sure it's added to your env path.

**Comment by tushiee** [comment]
It works now, Valet works, Laravel works, everything works!
Thank you very much man, do you maybe have Skype or Discord (only for chat tho) so I can maybe hit you up when I got a problem again? :P

**Comment by cretueusebiu** [comment]
Only Github. Also make sure to update to the latest version because I just fixed an issue for sites with SSL https://github.com/cretueusebiu/valet-windows/releases/tag/2.0.8
