### ISSUE TITLE
Backslash error: Valet installation fails

### ISSUE THREAD

**Issue by redesiigner** [cretueusebiu/valet-windows#71]
When installing valet on windows 10, installation fails with:

  [ErrorException]
  copy(C:\Users\xxx\AppData\Roaming\Composer\vendor**/**cretueusebiu**/**valet-windows**/**bin\acrylic\AcrylicService.exe): failed to open stream: Resource temporarily unavailable

There are incorrect / where \ should be, so it can't find the files.
This is due to the portation from linux, i think.

Best regards and thanks for your work,
Patrick

**Comment by cretueusebiu** [comment]
You get "Resource temporarily unavailable" when you have previously installed Valet and not stopped the services. 
Run `valet stop` and `valet uninstall` and then try to install it again. Make sure to run your terminal as administrator.

**Comment by ramakun-69** [comment]
Could not delete C:\Users\X260\AppData\Roaming\Composer\vendor/cretueusebiu
  /valet-windows\bin\acrylic\AcrylicService.exe:
  This can be due to an antivirus or the Windows Search Indexer locking the f
  ile while they are analyzed



how to fixed it
