### ISSUE TITLE
Possible to Run Multiple Versions of php?

### ISSUE THREAD

**Issue by CreateSean** [cretueusebiu/valet-windows#73]
Is it possible to run multiple versions of php?

I have some older projects which need to be on php 5.6 but my new projects are all on php 7.1 Is there a way to set a php version on a per project basis? ideally I'd set php 7.1 as default and then override it for projects that need an earlier version.

**Comment by cretueusebiu** [comment]
Not per project, but you can stop Valet (`valet stop`) rename the current `C:\php` folder to something else and installing another version. Then when you need to switch back do the same thing. 

If you use it often, I guess you can have some bash scripts that run the `valet stop` and rename the folders.

**Comment by CreateSean** [comment]
OH.. not ideal at all.
