### ISSUE TITLE
Doesn't Work with PIA VPN running

### ISSUE THREAD

**Issue by CreateSean** [cretueusebiu/valet-windows#74]
I have a VPN I run all the time. I was unable to get Valet-windows to work unless I disable the vpn. Is this a bug or something that cannot be resolved.

The VPN I'm using is PIA https://www.privateinternetaccess.com/

**Comment by cretueusebiu** [comment]
This version of Valet is using [Acrylic DNS Proxy](http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome) and in some cases, like when you don't have a network connection or in your case some custom network from the VPN might not work.

The alternative would be to add the domains manually in your hosts file.
