### ISSUE TITLE
Fatal error when trying to access the command

### ISSUE THREAD

**Issue by adamszigeti** [cretueusebiu/valet-windows#75]
After a fresh install with `composer global require cretueusebiu/valet-windows`, I get the following error message, even when just running `valet` command for sanity check:

```
> valet
PHP Fatal error:  Cannot redeclare info() (previously declared in C:\Users\xxx\AppData\Roaming\Composer\vendor\laravel-zero\foundation\src\Illuminate\Foundation\helpers.php:500) in C:\Users\xxx\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\cli\includes\helpers.php on line 30
```

Now of course, this is an error on my specific machine, for I have Laravel Zero installed globally (at least, in this instance), but I still think it's inappropriate to use global functions instead of namespacing them in a library, like `use function Cretueusebiu\Valet\{info, warning, ...};` (it's not just Laravel Zero, it conflicts with a lot of other, laravel-related package as well).

> **NOTE:** I understand that this package has nothing to do with Laravel Zero or any other package; the problem is the inappropriate assumption associated with using global functions in such a general-purpose library as this one).

By the way, thank you for all your work you have put into this package, it really makes my day-to-day work easier (I plan to open a PR about this later when I have time, attempting to fix this)! :)

**Comment by cretueusebiu** [comment]
That's how the original [Valet](https://github.com/laravel/valet) was made.  

A solution they recommended is to use this package https://github.com/consolidation/cgr.

But it should be really namespaced. If you could submit a PR, that would be great.

**Comment by adamszigeti** [comment]
Oh I did not know that the original Valet uses global functions as well. CGR seems to be a great solution for now though, thanks (will try to look into this later anyways)!
