### ISSUE TITLE
First step fails...  Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by rebz** [cretueusebiu/valet-windows#78]
`Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:35`

![image](https://user-images.githubusercontent.com/628385/36631471-54ea509a-1946-11e8-8579-d278643931e0.png)

**Comment by cretueusebiu** [comment]
You have to type `Y` to allow the execution of the script.

**Comment by rebz** [comment]
Definitely did. Multiple times. Uppercase. Lowercase. Tried `a`, `A`, `y`, and `Y`. The problem still isn't solved.

**Comment by cretueusebiu** [comment]
Download [php71.ps1](https://github.com/cretueusebiu/valet-windows/blob/master/bin/php71.ps1) manually and install it.

Or just download the zip directly from http://windows.php.net/

**Comment by rebz** [comment]
I'll give that a try. Thanks!

**Comment by dqfan2012** [comment]
@cretueusebiu I know this issue has been closed.  It might be nice to recommend that the following two steps be used for PowerShell 5+.

- Make sure IE has been run at least once (PowerShell uses the IE engine to download things).
- If you're connecting to a website that requires SSL/TLS, then you want to use **[System.Net.ServicePointManager]::SecurityProtocol = [System.N
et.SecurityProtocolType]::Tls12;** before invoking the web request.

See the full command:

```
Set-ExecutionPolicy RemoteSigned; [System.Net.ServicePointManager]::SecurityProtocol = [System.N
et.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing -Uri "https://github.com/cretueusebiu/valet-windows/
raw/master/bin/php72.ps1" -OutFile $env:temp\php72.ps1; ."$env:temp\php72.ps1"
```

**Comment by rebz** [comment]
@dqfan2012 Hey, that trick for TLS 1.2 worked. Thank you very much!

**Comment by dqfan2012** [comment]
@rebz you're welcome

**Comment by nickmak** [comment]
@cretueusebiu Please update your README.md with what @dqfan2012 wrote for the solution of "First Steps..." using SSL/TLS. His assistance resolved the same issue the OP had.
