### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by mattyforth** [cretueusebiu/valet-windows#79]
I'm unable to install the package.

I have ran a `composer global remove cretueusebiu/valet-windows` and it appears to be successful, however valet remains installed and still auto-starts its nginx service.

Any help would be appreciatted

**Comment by cretueusebiu** [comment]
You have to run `valet stop` and `valet uninstall`.

**Comment by julkar9** [comment]
I have run valet stop and valet uninstall .

BUT DNS is not working . My WIFI connection drop automatic .

**Comment by weerdenburg** [comment]
Maybe you forgot to undo the proxy settings of Acrylic DNS?
During the 1st. install you have done the following steps to make it work:
https://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration

_As a side note:
When I run 'valet stop', I can't visit any Internet page, I have fixed this by adding 8.8.8.8 (Google DNS) as secondary DNS entry._

**Comment by icolumbro** [comment]
Unfortunately, this port of Valet for Windows does not work on my workstation with Windows 10 (if I try to visit myblog.test the Laravel site does not appear, even though myblog.test responds to ping).
How can I uninstall **everything**?
I mean, apart from doing "_valet stop_" and "_valet uninstall_", how do I delete Acrylic DNS, nginx and all the files installed in the system?

**Comment by tmsss** [comment]
I have ran valet stop and valet uninstall, but I also had to run composer global remove cretueusebiu/valet-windows. 

After this you also have to remove the valet folder under C:\Users\<your-username>\.config and, in case you've installed them, the nginx and phpfpm valet services from the windows registry. It would be cool if there was an automated process to do this.

**Comment by vickyjodha** [comment]
valet(laravel 6) removed for windows

**Comment by ardhikavp** [comment]
Changing the DNS to google DNS so I can get my internet connection again, and then running again composer global remove cretueusebiu/valet-windows. The no internet problem because of valet DNS changing solved for me.
