### ISSUE TITLE
valet secure created ssl cert is 1 hour advance

### ISSUE THREAD

**Issue by wargodz009** [cretueusebiu/valet-windows#81]
im getting error on its ssl status that says:
the certificate has expired or is not yet valid

upon checking the details 
the certificate valid_from date is ahead of 1 hours upon creating the certificate.

i live in philippines btw php timezone is asia/manila

**Comment by leexin** [comment]
I'm facing the same issue. valet secure broke because SSL date created is in the future.

**Comment by mharkrollen2** [comment]
I have the same issue. Please fix

**Comment by OliverW21** [comment]
Still doesn't really work. It creates a cert that is 2 hours in front. (Germany Europe/Berlin)
Fixed it by using another timezone that is a few hours behind (America/Havana)

```
[Date]
date.timezone=America/Havana

**Comment by cretueusebiu** [comment]
Can you try the latest version (2.1.1) ?
