### ISSUE TITLE
How to use xip.io or nip.io with valet-windows

### ISSUE THREAD

**Issue by simioluwatomi** [cretueusebiu/valet-windows#83]
I have a project with 3 sub-domains ```admin.example.test```, ```app.example.test```, ```api.example.test```. To share the project with xip.io, I have followed the steps mentioned [here](https://github.com/laravel/valet/issues/450#issuecomment-333377135) and [here](https://github.com/laravel/valet/issues/450#issuecomment-333397438).

I also modified my ```APP_URL = http://my_local_ip_address.xip.io``` because my route groups are structured like so

```
Route::group(['namespace' => 'Web', 'domain' => env('APP_URL')], function () {
    // more code here
});

Route::group(['namespace' => 'Web\Auth', 'domain' => 'app.' . env('APP_URL')], function () {
    // more code here
});
```
Then I ran ```valet link my_local_ip_address.xip.io``` and ```valet link {subdomain}.my_local_ip_address.xip.io``` for all sub-domains. Thereafter, I added entries to my hosts file for each of those subdomains just in case. The result is that all subdomain routes give a ```Valet 404 - Not Found``` error but ```my_local_ip_address.xip.io``` routes works just fine.

How do I make this work for all sub-domains in the project? Thanks

**Comment by cretueusebiu** [comment]
Inside your project you'll just have to link the name of the subdomain (`valet link admin`).

```bash
cd project/

# link main site
valet link my_local_ip_address.xip.io

# link subdomain admin.my_local_ip_address.xip.io
valet link admin
```
