### ISSUE TITLE
Nginx not serving updated files

### ISSUE THREAD

**Issue by alystair** [cretueusebiu/valet-windows#88]
Sometimes Nginx does not recognize files have changed, as such browsers reload from disk cache - since Valet is a development environment wouldn't it make sense to specifically disable caching mechanisms?

**Comment by cretueusebiu** [comment]
Not sure that's related to Valet. Maybe just the browser cache in general.

**Comment by alystair** [comment]
Nginx is specifically returning cache tags in response header

```
Date: Sat, 02 Jun 2018 19:29:15 GMT
ETag: W/"5b1126c5-4a3"
Last-Modified: Fri, 01 Jun 2018 10:58:13 GMT
```

**Comment by alystair** [comment]
I think it actually be be the Valet middleware not checking if the file has changed, not Nginx - since requests are passed through server.php

**Comment by cretueusebiu** [comment]
It's the default configuration as the [original Valet](https://github.com/laravel/valet). So try checking there.
