### ISSUE TITLE
nginx service can not start

### ISSUE THREAD

**Issue by taisang1996** [cretueusebiu/valet-windows#9]
nginx: [emerg] CreateFile() "C:\Users	aisang/.valet/Log/nginx-error.log" failed (123: The filename, directory name, or volume label syntax is incorrect)

my username is taisang
C:\Users\taisang\

C:\Users\taisang\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx\conf\nginx.conf
```
# user taisang staff;
worker_processes auto;

events {
    worker_connections  1024;
}

http {
    include mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout  65;
    server_names_hash_bucket_size 64;

    gzip  on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;

    gzip_types
    application/atom+xml
    application/javascript
    application/json
    application/rss+xml
    application/vnd.ms-fontobject
    application/x-font-ttf
    application/x-web-app-manifest+json
    application/xhtml+xml
    application/xml
    font/opentype
    image/svg+xml
    image/x-icon
    text/css
    text/plain
    text/x-component;

    include C:\Users\taisang/.valet/Nginx/*.conf;
    include servers/*;
    include ../valet/valet.conf;
}
```

can

**Comment by taisang1996** [comment]
![image](https://cloud.githubusercontent.com/assets/8613316/22683837/6ff9540c-ed4c-11e6-9436-8728e8f88b7a.png)

**Comment by cretueusebiu** [comment]
Try to install it with CMD and run it has administrator.

**Comment by taisang1996** [comment]
I have fixed that bug by wrap $_SERVER['HOME'] with addslashes function.

Because when using windows. My home path is `C:\Users\taisang` the character \t nginx is replace with Tab. 
Fixed that by using `C:\\Users\\taisang` instead of one backslash in the nginx conf should word.


In file `server.php`
```
define('VALET_HOME_PATH', addslashes($_SERVER['HOME']).'/.valet');
```

**Comment by cretueusebiu** [comment]
I'll make sure to fix this in the next release.
