### ISSUE TITLE
AcrylicDNS not working

### ISSUE THREAD

**Issue by edalzell** [cretueusebiu/valet-windows#91]
Apologies if this is not the right venue for this.

I simply cannot get Valet work properly on my Windows 10 machine. If I set up AcrylicDNS as per the docs, I can access valet sites but not external sites. If I remove those DNS settings I can access external sites but not valet sites.

I have gotten this going on another Windows machine (my dad's) but I cannot, for the life of me, figure out why AcrylicDNS is not passing the external requests on to the normal DNS.

Any ideas on where I can look to figure this out?

Thanks!

**Comment by edalzell** [comment]
I have used [this](https://github.com/cretueusebiu/valet-windows/issues/89#issuecomment-402908705) as a work-around at the moment.

**Comment by jesseyofferenvan** [comment]
You can try making a virtual network adapter and set it's settings with the AcrylicDNS settings as per the documentation. This should work as well.

**Comment by hiddehs** [comment]
Stumbled on the same problem when the Windows 10 config (https://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration) was not working. After troubleshooting Acrylic by trying to start the console version, after stopping the services of course, I still got a 0.0.0.0 binding error on port 53.

**Windows 10 Fix: ** edit your %appdata%\Composer\vendor\cretueusebiu\valet-windows\bin\acrylic\AcrylicConfiguration.ini and change LocalIPv4BindingAddress to 127.0.0.1. Make sure you're using the AcrylicWindows10Configuration on your network adapter. To use this 'new' Acrylic config you can simply restart valet by running `valet restart`.

**Comment by muhba25** [comment]
Maybe [this article](https://www.itugasmu.com/2022/09/how-to-fixed-acrylicdns-service-stopped.html) can help you for the issue
