### ISSUE TITLE
Services not installed, valet not starting up

### ISSUE THREAD

**Issue by carlossantoswd** [cretueusebiu/valet-windows#92]
Today I turned on the PC and the valet was not working (I usually hibernate the PC).
I rebooted the PC and it did not work.

I checked the Log folder, it was empty.
I uninstalled the Valet

**Uninstall / install steps**
- valet stop
- valet uninstall
- valer install

It did not work, I forced reinstall again:

- valet stop
- valet uninstall
- composer global remove cretueusebiu/valet-windows
- composer clearcache
- composer global require cretueusebiu/valet-windows
- valet install

I have not been able to access my * .test yet

I checked the services, acrylicdns running, valet_nginx, and valet_phpfpm are not installed.

All the commands were executed as administrator and in the folder c: /

**Comment by cretueusebiu** [comment]
Hi, have you tried to configure the Acrylic DNS manually ? http://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration

**Comment by carlossantoswd** [comment]
yes, of course,  but the problem is: another services aren't installed when
I install valet-windows

Em qua, 1 de ago de 2018 às 01:55, Cretu Eusebiu <notifications@github.com>
escreveu:
