### ISSUE TITLE
Can't access valet sites

### ISSUE THREAD

**Issue by DMTcorp** [cretueusebiu/valet-windows#94]
Hi, 
valet installed and ngnix, php-fpm services running. Domain changed to .appdev and project linked.

I am getting ERR_NAME_NOT_RESOLVED when trying to open project.appdev. 

Using Acrylic DNS - idk if it's working. I've just configured my ipv4 dns to 127.0.0.1, alternative to 8.8.8.8 (to make my internet works) and ipv6 ::1.

Anyone?

Regards,
Matt

**Comment by mpash** [comment]
I'm having the same issue.

**Comment by DMTcorp** [comment]
I am using Laragon instead, working well

**Comment by malic0** [comment]
http://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration
Perform this Configuration, Then Disable and enable your Network Adapter...

**Worked for Me**
