### ISSUE TITLE
Uninstallation Issue

### ISSUE THREAD

**Issue by iamantu93** [cretueusebiu/valet-windows#95]
Cannot fully uninstall using 
`composer global remove cretueusebiu/valet-windows` .The acrylic service is not uninstalled. So you have to manually stop the service from services.msc. Then remove the package folder from composer bin.

**Comment by cretueusebiu** [comment]
You have to run `valet uninstall` first, then composer global remove

**Comment by KaziJahurul** [comment]
I have been trying to run the `valet uninstall` command from powershell but it says valet is not recognized. Here is a screenshot. https://prnt.sc/ph9k6l

Please let me know from which directory I should run valet commands ?

**Comment by navaneeth-raman-bhaskar** [comment]
Failed to stop service [phpcgixdebugservice].   `'"C:/Users/Navaneeth Raman Bhaskar/.config/valet\Services\phpcgixdebugservice"'` is not recognized as an internal or external command,                                                                                                                  operable program or batch file.

**Comment by cretueusebiu** [comment]
@navaneeth-raman-bhaskar Even after the latest update ?

**Comment by navaneeth-raman-bhaskar** [comment]
@cretueusebiu  Previous update helps to install valet.
Previously installed valet windows services caused the problem.
 `valet stop , valet uninstall`  cannot remove the services installed so, below method works.

1. Start the registry editor (regedit.exe)
2. Move to the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services key
3. Select the key of the service you want to delete _(valet related)_
4. From the Edit menu select Delete
5. You will be prompted "Are you sure you want to delete this Key" click Yes
6. Exit the registry editor
7. Restart computer

Now my problem fixed

**Comment by aryapanangsang** [comment]
You must stop Acrylic DNS Proxy from services.msc and than run the command `composer global remove cretueusebiu/valet-windows`

**Comment by kelvinjulian** [comment]
thankss it works
