### ISSUE TITLE
Missing valet dependiencies error

### ISSUE THREAD

**Issue by atefBB** [cretueusebiu/valet-windows#96]
I install valet as described in the README file and when I run `valet install` command I got this error : 
![valet-install-prob](https://user-images.githubusercontent.com/10966925/44897977-74b84b00-acf5-11e8-9dde-0f5bcf4c981b.PNG)

**Comment by cretueusebiu** [comment]
You're trying to install Valet for Linux. This is the Windows version.

**Comment by atefBB** [comment]
Thx @cretueusebiu !
Nope! I use `windows`!

**Comment by cretueusebiu** [comment]
The error says you're using `https://github.com/cpriego/valet-linux`
